export type AlprAdvanceSearchModel = {
    recId           :number
    capturePlate    :string,
    numberPlate    :string,
    hotlistName     :string,
    capturedAt      :string,
    stateName       :string,
    unitId          :string,
    user            :string,
    confidence      :string,
    ticketNumber    :string,
    longitude       :number,
    latitude        :number,
    ncicNumber      :string,
    dateOfInterest  :string,
    licenseYear     :string,
    licenseType     :string,
    vehicleYear     :string,
    vehicleMake     :string,
    vehicleModel    :string,
    insertType      :string,
    status          :string,
    note            :string,
    firstName       :string,
    lastName        :string,
    violationInfo   :string,
  }