export interface LicensePlate {
    recId: number,
    ncicNumber: string,
    dateOfInterest: any,
    licensePlate: string,
    stateId: string,
    licenseYear: string,
    licenseType: string,
    vehicleMake: string,
    vehicleYear: string
    vehicleModel: string,
    vehicleStyle: string,
    vehicleColor: string,
    note: string,
    insertType: string,
    createdOn: string,
    lastUpdatedOn: string,
    status: string,
    firstName: string,
    lastName: string,
    alias: string,
    violationInfo: string,
    notes: string,
    importSerialId: string,
    agencyId: string,
    
}