export const defaultDevice = "-- Select device --"
export const defaultParameter = "-- Select parameter --"
export const defaultCriteria = "-- Select criteria --"
export const defaultBookmark = "-- Select bookmark --"
export const defaultAction = "-- Select action --"
export const defaultIcon = "-- Select icon --"
export const defaultCategory = "-- Select category --"
export const defaultCamera = "-- Select camera --"
