export const resources = {
    // en: {
    //   translation: {
    //     "assets": "en-Assets",
    //     "Show / hide columns": "en-Show / hide columns",
    //     "Close" : "en-Close",
    //     "Reset to default" : "en-Reset to default",
    //     "Customize columns": "en-Customize columns",
    //     "Save and close" : "en-Save and close",
    //     "Save as preset" : "en-Save as preset",
    //     "Actions": "en-Actions",
    //     "ID":"en-ID",
    //     "Asset Thumbnail":"en-Asset Thumbnail",
    //     "Asset Name":"en-Asset Name",
    //     "Asset Type":"en-Asset Type",
    //     "Unit":"en-Unit",
    //     "Categories":"en-Categories",
    //     "Device":"en-Device",
    //     "Station":"en-Station",
    //     "Recorded By":"en-Recorded By",
    //     "Expiry Date":"en-Expiry Date",
    //     "Status":"en-Status",
    //     "":"en-",
    //     "":"en-",
    //     "":"en-",
    //     "":"en-",
    //   }
    // }

    en: {
      translation: {
        // --------- Asset Lister ----------
        "Login To Getac Enterprise using Getac Authentication":"Login To Getac Enterprise using Getac Authentication",
        "Inspiring statement about Getac / Getac product that is relevant to user":"Inspiring statement about Getac / Getac product that is relevant to user",
        "You are accessing a restricated information system. Your usage may be monitored, recoreded and subject to audit. Unauthorized use of the system is prohibited and may be subject to criminal and/or civil penalities. By using this system and clicking Log In, you consent to your usage being monitored and recorded.":"You are accessing a restricated information system. Your usage may be monitored, recoreded and subject to audit. Unauthorized use of the system is prohibited and may be subject to criminal and/or civil penalities. By using this system and clicking Log In , you consent to your usage being monitored and recorded.",
        "Log_In":"Log In",
        "assetDataTable":"Assets",
        "userGroup_DataTable":"User Groups",
        "Tables_columns_filter":"Tables columns filter",
        "Close":"Close",
        "Reset_to_default":"Reset to default",
        "Clearall_filters":"Clear all filters",
        "Customize_columns":"Customize columns",
        "Save_and_close":"Save and close",
        "Saveas_preset":"Save as preset",
        "Actions":"Actions",
        "ID":"ID",
        "Asset_Thumbnail":"Asset Thumbnail",
        "Asset_ID":"Asset ID",
        "Asset_Type":"Asset Type",
        "Unit":"Unit",
        "Category":"Category",
        "Description":"Description",
        "Retention_Span":"Retention Span",
        "Device":"Device",
        "Station":"Station",
        "Recorded_By":"Recorded By",
        "User_Name":"Username",
        "Captured":"Captured",
        "File_Status":"File Status",
        "Select_All":"Select all",
        "Grouped_Assets":"Grouped Assets",
        "Assign_User":"Assign User",
        "Modify_Retention":"Modify Retention",
        "Share_Asset":"Share Asset",
        "Video_Analysis":"Video Analysis",
        "Audio_Analysis":"Audio Analysis",
        "Audio_Source":"Audio Source",
        "Select_Audio_Source":"Select Audio Source",
        "Submit_For_Analysis":"Submit For Analysis",
        "Add_to_asset_bucket":"Add to asset bucket",
        "Edit_Category_and_Form":"Edit Category and Form",
        "Categorize":"Categorize",
        "Email":"Email",
        "File":"File",
        "Metadata":"",
        "Evidence_overlaid_video":"Evidence overlaid video",
        "Metadata_overlaid_video":"Metadata overlaid video",
        "Link_asset":"Link asset",
        "Link_to_this_group":"Link to this group",
        "Move_asset":"Move asset",
        "Move_to_this_group":"Move to this group",
        "Restrict_access":"Restrict access",
        "Remove_from_asset_bucket":"Remove from asset bucket",
        "Set_as_primary_asset":"Set as primary asset",
        "Assign_to_case":"Assign to case",
        "TBD":"TBD",
        "Open_in_Getac_AI_tools_App":"Open in Getac AI tools App",
        "Users":"Users",
        "Apply_to_all_assets_in_the_group":"Apply to all assets in the group",
        "Save":"Save",
        "Cancel":"Cancel",
        "You_are_attempting_to":"You are attempting to",
        "close":"close",
        "the_modal_dialog":"the modal dialog.",
        "If_you_close_the_modal_dialog,":"If you close the modal dialog,",
        "any_changes_you_ve_made_will_not_be_saved.":"any changes you've made will not be saved.",
        "You_will_not_be_able_to_undo_this_action.":"You will not be able to undo this action.",
        "Are_you_sure_you_would_like_to":"Are you sure you would like to",
        "Yes":"Yes",
        "No,_do_not_close":"No, do not close",
        "Success:_You_have_saved_the_asset_categorization":"Success: You have saved the asset categorization",
        "Error_We_re_sorry._The_form_was_unable_to_be_saved._Please_retry_or_contact_your_Systems_Administrator":"Error: We're sorry. The form was unable to be saved. Please retry or contact your Systems Administrator",
        "Indicates_required_field":"Indicates required field",
        "Please_enter_the_reason_for_editing_the_form.":"Please enter the reason for editing the form.",
        "Category_form_edit_reason":"Category form edit reason",
        "Editing_the_category_form_requires_a_reason":"Editing the category form requires a reason",
        "Please_confirm":"Please confirm",
        "Please_be_aware_that_by_removing_this_category,_you_are_reducing_the_assets_lifetime_and_the_asset_will_expire":"Please be aware that by removing this category, you are reducing the assets lifetime and the asset will expire",
        "in":"in",
        "Hours.":"Hours.",
        "Please_be_aware_that_by_removing_this_category,_you_are_reducing_the_assets_lifetime_and_the_asset_will_expire_in":"Please be aware that by removing this category, you are reducing the assets lifetime and the asset will expire in",
        "Unclassified_retention_policy_of_station_will_be_applied_on_this_evidence_group.":"Unclassified retention policy of station will be applied on this evidence group.",
        "Success_You_have_saved_the_asset_categorization":"Success: You have saved the asset categorization",
        "We_re_sorry._The_form_was_unable_to_be_saved._Please_retry_or_contact_your_Systems_Administrator":"We 're sorry. The form was unable to be saved. Please retry or contact your Systems Administrator",
        "You_are_attempting_to_remove":"You are attempting to remove",
        "Do_you_want_you_continue_with_removing_the_category?":"Do you want you continue with removing the category?",
        "Yes,_remove-category":"Yes, remove category",
        "No,_do_not_remove_category":"No, do not remove category",
        "category":"category",
        "Category_Title_Placeholder_Here":"Category Title Placeholder Here",
        "Attention":"Attention",
        "There_is_no_form_response_for_the_category_named,":"There is no form response for the category named,",
        "Please_sav_to_continue.":"Please save to continue.",
        "Back":"Back",
        "Required":"Required",
        "Category_Forms":"Category Forms",
        "is_required":"is required",
        "Category_form":"Category form'",
        "Edit_category":"Edit category",
        "Next":"Next",
        "Skip_category_form_and_save":"Skip category form and save",
        "Choose_Category":"Choose Category",
        "From_the_field_below,_select_one_or_more_relevant_category.":"From the field below, select one or more relevant category.",
        "Removing_the_category_requires_a_reason":"Removing the category requires a reason",
        "Please_enter_the_reason_for_removing_the_category.":"Please enter the reason for removing the category.",
        "Category_removal_reason":"Category removal reason",
        "Extend_retention_by_days":"Extend retention by days",
        "Extend_retention_Indefinitely":"Extend retention Indefinitely",
        "User":"User",
        "Revert_to_original_retention":"Revert to original retention",
        "Retention_Extended":"Retention Extended",
        "Retention_Reverted":"Retention Reverted",
        "Original_Retention:":"Original Retention:",
        "Current_Retention:":"Current_Retention:",
        "Extend":"Extend",
        "Assets":"Assets",
        "Search_assets_by_ID#_case#_CAD#_categories_etc.":"Search assets by ID#, case#, CAD#, categories, etc.",
        "Infinite":"Infinite",
        "Days":"Days",
        "Hours":"Hours",
        "Share_email_sent_to_recipients":"Share email sent to recipients",
        "Include_Metadata":"Include Metadata",
        "Link_Expiry":"Link Expiry",
        "Viewable_once":"Viewable once",
        "Downloadable":"Downloadable",
        "Please_Select":"Please Select",
        "Search_by":"Search by",
        "Date_and_Time":"Date and Time",
        "Add_search_criteria":"Add search criteria",
        "Reset_advanced_search":"Reset advanced search",
        "Advanced_Search":"Advanced Search",
        "day":"day",
        "days":"days",
        "second":"second",
        "Search_Results":"Search Results",
        "next_30_days":"next 30 days",
        "Search_Assets":"Search Assets",
        "Search":"Search",
        "Confirm":"Confirm",
        "Are_you_sure_want_to_restrict_access_to_the_selected_asset(s)?":"Are you sure want to restrict access to the selected asset(s)?",
        "Access_to_the_selected_asset(s)_will_be_restricted_to_user_groups_with_the_view_locked_asset_permission.":"Access to the selected asset(s) will be restricted to user groups with the view locked asset permission.",
        "Delete":"Delete",
        "the":"the",
        "Notes":"Notes",
        "Bookmark":"Bookmark",
        "action":"action",
        "the_dialogue?":"the dialogue?",
        "Form":"Form",
        "Edit":"Edit",
        "Showless":"Showless",
        "Read_More":"Read More",
        "Map":"Map",
        "Bookmarks":"Bookmarks",
        "Success":"Success",
        "Note_Sucessfully_Updated":"Note Sucessfully Updated ",
        "Bookmark_Edited_Sucessfully":"Bookmark Edited Sucessfully ",
        "Bookmark_Deleted_Sucessfully":"Bookmark Deleted Sucessfully ",
        "Note_Deleted_Sucessfully":"Note Deleted Sucessfully ",
        "Search_Bookmark":"Search Bookmark",
        "Search_by_Name_keyword_etc.":"Search by Name, keyword, etc.",
        "Search_Notes":"Search Notes",
        "Asset_Detail:_":"Asset Detail: ",
        "Information":"Information",
        "GROUPED_AND_RELATED_ASSETS":"GROUPED AND RELATED ASSETS",
        "Captured_Date":"Captured Date",
        "Owners":"Owners",
        "Unit":"Unit",
        "CheckSum":"CheckSum",
        "Video_Duration":"Video Duration",
        "Size":"Size",
        "Retention":"Retention",
        "Categories":"Categories",
        "Copyright_©_Getac_Video_Solutions_Inc._and_its_subsidiaries._All_rights_reserved._|_Enterprise_Version":"Copyright © Getac Video Solutions, Inc. and its subsidiaries. All rights reserved. | Enterprise Version",
        "is_successfully_set_as_primary_asset":"is successfully set as primary asset",
        "You_are_sure_want_to_make":"You are sure want to make",
        "the_primary_asset?":"the primary asset?",
        "Set_as_primary_asset":"Set as primary asset",
        "Export":"Export",
        "Asset_Assignees_updated":"Asset Assignees updated",
        // -------------------------

        // --------- User ----------
        "Send_Activation_Link":"Send Activation Link",
        "Resend_Activation_Link":"Resend Activation Link",
        "Generate":"Generate",
        "Copy":"Copy",
        "Require_user_to_change_password_on_next_login":"Require user to change password on next login",
        "Password":"Password",
        "Confirm_Password":"Confirm Password",
        "Generate_Temporary_Password":"Generate Temporary Password",
        "Manually_Set_Password":"Manually Set Password",
        "You_have_created_the_user_account.":"You have created the user account.",
        "You_have_resent_the_activation_link.":"You have resent the activation link.",
        "You_have_updated_the_user_account.":"You have updated the user account.",
        "Please_provide_a_valid_User_name.":"Please provide a valid User name.",
        "User_name_must_contain_atleast_three_characters.":"User name must contain atleast three characters.",
        "User_name_must_not_exceed_128_characters.":"User name must not exceed 128 characters.",
        "Please_provide_a_valid":"Please provide a valid",
        "must_contain_atleast_three_characters.":"must contain atleast three characters.",
        "must_not_exceed_128_characters.":"must not exceed 128 characters.",
        "First_Name":"First Name",
        "First_Name_is_required":"First Name is required",
        "Last_Name":"Last Name",
        "Last_Name_is_required":"Last Name is required",
        "Username_is_required":"Username is required",
        "Email_is_required":"Email is required",
        "Please_provide_a_valid_email_address":"Please provide a valid email address",
        "Password_is_required":"Password is required",
        "Confirm_Password_is_required":"Confirm Password is required",
        "Passwords_are_not_same":"Passwords are not same",
        "(Link_will_be_sent_after_saving_this_form.)":"(Link will be sent after saving this form.)",
        "Please_provide_a_valid_phone_number.":"Please provide a valid phone number.",
        "Number_must_not_exceed_15_characters.":"Number must not exceed 15 characters.",
        "User_group_is_required":"User group is required",
        "Middle_Initial":"Middle Initial",
        "Phone_Number":"Phone Number",
        "User_Group":"User Group",
        "Deactivation_Date":"Deactivation Date",
        "User_Password_Setup":"User Password Setup",
        "'user_form'":"'user form'",
        "If_you_close_the_form":"If you close the form",
        "the_form?":"the form?",
        "Yes_close":"Yes, close",
        "custom_range":"custom range",
        "No_Status":"No Status",
        "Status":"Status",
        "Last_Login":"Last Login",
        "Groups":"Groups",
        "Create_User":"Create User",
        "Filter":"Filter",
        "Unlock_user_account":"Unlock user account",
        "Yes_unlock_user_account":"Yes, unlock user account",
        "No_do_not_unlock":"No, do not unlock",
        "Deactivate_user_account":"Deactivate user account",
        "Yes_deactivate_user_account":"Yes, deactivate user account",
        "No_do_not_deactivate":"No, do not deactivate",
        "You_have_unlocked_the_user_account.":"You have unlocked the user account.",
        "You_have_deactivated_the_user_account.":"You have deactivated the user account.",
        "Assets_Action_Menu":"Assets Action Menu",
        "the_following_user_account:":"the following user account:",
        "Please_confirm_if_you_would_like_to":"Please confirm if you would like to",
        "this_user_account.":"this user account.",
        "Edit_user":"Edit user",
        "Unlock_account":"Unlock account",
        "Deactivate_account":"Deactivate account",
        // ------------------------------

        // --------- User Group----------
        "Group_Name":"Group Name",
        "Total_Users_Assigned":"Total Users Assigned",
        "Create_Group":"Create Group",
        "GROUP_NAME":"GROUP NAME",
        "USERS":"USERS",
        "APPLICATION_PERMISSIONS":"APPLICATION PERMISSIONS",
        "DATA_PERMISSIONS":"DATA PERMISSIONS",
        "User_group_saved_successfully.":"User group saved successfully.",
        "We_re_sorry_The_group_information_users_and_application_permissions_were_unable_to_be_saved__Please_retry_or_contact_your_System_Administrator.":"We're sorry. The group information, users, and application permissions were unable to be saved. Please retry or contact your System Administrator.",
        "We_re_sorry_The_data_permissions_were_unable_to_be_saved._Please_retry+or_contact_your_System_Administrator.":"We're sorry. The data permissions were unable to be saved. Please retry or contact your System Administrator.",
        "'user_group_form'":"'user group form'",
        "Module_Names":"Module Names",
        "Basic_level":"Basic level",
        "Advanced_level":"Advanced level",
        "Restricted_level":"Restricted level",
        "Apply_application_permissions_from":"Apply application permissions from",
        "All":"All",
        "Uncategorized":"Uncategorized",
        "No_Station":"No Station",
        "Permission_Type":"Permission Type",
        "Permission_Value":"Permission Value",
        "Permission_Level":"Permission Level",
        "Add_data_permissions":"+ Add data permissions",
        "Group_name_is_required":"Group name is required",
        "No_Groups":"No Groups",
        // ----------------------------
        
        // --------- Station ----------
        "Address":"Address",
        "Create_Station":"Create Station",
        "Station_deleted":"Station deleted",
        "The_station_cant_be_deleted__please_check_for_dependent_units_and_assets":"The station can't be deleted, please check for dependent units and assets",
        "Delete_station":"Delete station",
        "No":"No",
        "unlock":"unlock",
        "deactivate":"deactivate",
        "delete":"delete",
        "the_following_user_account":"the following user account",
        "You_are_attempting_to_delete_the_station":"You are attempting to delete the station",
        "Are_you_sure_you_would_like_to_delete_the_station?":"Are you sure you would like to delete the station?",
        "Edit_station":"Edit station",
        "View_default_unit_templates":"View default unit templates",
        "Station_Name_is_required":"Station Name is required",
        "Minimum_5_characters_are_allowed.":"Minimum 5 characters are allowed.",
        "Pass_Code_is_required":"Pass Code is required",
        "Only_alphabets_and_digits_are_allowed.":"Only alphabets and digits are allowed.",
        "Success_You_have_saved_the_Station":"Success: You have saved the Station",
        "Station_Name":"Station Name",
        "Name":"Name",
        "Latitude":"Latitude",
        "Longitude":"Longitude",
        "Location":"Location",
        "Map_location":"Map location",
        "Street_Address":"Street Address",
        "Pass_Code":"Pass Code",
        "Station_Settings":"Station Settings",
        "Data_Retention_Policy":"Data Retention Policy",
        "Retention_Policy_is_required":"Retention Policy is required",
        "Data_Upload_Policy":"Data Upload Policy",
        "Upload_Policy_is_required":"Upload Policy is required",
        "BlackBox_Retention_Policy":"BlackBox Retention Policy",
        "SSID":"SSID",
        "Unit_Templates":"Unit Templates",
        "Select_location_on_the_map":"Select location on the map",
        "Save_Location":"Save Location",
        "Phone_Number_is_not_valid!":"Phone Number is not valid!",
        "Phone_Number":"Phone Number",
        // -------------------------
        
        // --------- Unit ----------
        "To_Get_ID":"To Get ID",
        "Success_You_have_saved_the_Default_Unit_Template":"Success: You have saved the Default Unit Template",
        "Manage_Default_Unit_Template":"Manage Default Unit Template",
        "Manage_Unit_Configuration":"Manage Unit Configuration",
        "Edit_template":"Edit template",
        "Clone_template":"Clone template",
        "Delete_template":"Delete template",
        "View_Change_Log":"View Change Log",
        "Are_you_sure_you_would_like_to_delete_template?":"Are you sure you would like to delete template?",
        "template":"template",
        "this":"this",
        "No_Version":"No Version",
        "No_type":"No type",
        "Default":"Default",
        "No_Indicator":"No Indicator",
        "Type":"Type",
        "Indicator":"Indicator",
        "Create_Template":"Create Template",
        "Change_Log":"Change Log: ",
        "Changes":"Changes",
        "Log_Time":"Log Time",
        // ---------------------------
        
        // --------- Header ----------
        "Getac_Command":"Getac Command",
        "Getac_Enterprise":"Getac Enterprise",
        "All_Stations":"All Stations",
        "Departments":"Departments",
        "Help":"Help",
        "User_Profile":"User Profile",
        "Logout":"Logout",
        "Home":"Home",
        "Cases":"Cases",
        "Units_&_Devices":"Units & Devices",
        "ALPR":"ALPR",
        "Plate_Captures":"Plate Captures",
        "Live_ALPR":"Live ALPR",
        "Manage_Hot_List":"Manage Hot List",
        "Manage_Hot_List_Data_Source":"Manage Hot List Data Source",
        "Manage_License_Plates":"Manage License Plates",
        "Admin":"Admin",
        "Manage_User_Groups_Permissions":"Manage User Groups & Permissions",
        "Manage_Users":"Manage Users",
        "Manage_Device_Unit_Templates":"Manage Device & Unit Templates",
        "Evidence(Dev)":"Evidence(Dev)",
        "Manage_Station":"Manage Station",
        // ---------------------------------
        
        // --------- Asset buctet ----------
        "An_asset_you_are_attempting_to_add_to_the_asset_bucket_has_already_been_added.":"An asset you are attempting to add to the asset bucket has already been added.",
        "You_have_added_the_selected_assets_to_the_asset_bucket.":"You have added the selected assets to the asset bucket.",
        "assets":"assets",
        "asset":"asset",  
        "removed_the_asset_bucket":"removed the asset bucket",
        "Asset_Bucket_can_be_used_to_build_cases_and_do_one_action_on_many_assets_at_the_same_time.":"Asset Bucket can be used to build cases and do one action on many assets at the same time.",
        "Asset_Bucket":"Asset Bucket",
        "Minimum_3_and_maximum_128_characters_are_allowed":"Minimum 3 and maximum 128 characters are allowed",
        "Only_alphabets_digits_and_,_-_are_allowed._Must_start_with_an_alphabet_only":"Only alphabets, digits and _, - are allowed. Must start with an alphabet only",
        "File(s)_failed_to_upload.":"File(s) failed to upload.",
        "File(s)_uploaded":"File(s) uploaded",
        "Asset_saved":"Asset_saved",
        "File_has_been_removed_successfully":"File has been removed successfully",
        "Your_Asset_Bucket":"Your Asset Bucket",
        "Please_add_metadata_to_finish_saving_your_uploaded_files":"Please add metadata to finish saving your uploaded files",
        "Add_metadata":"Add metadata",
        "Choose_asset_metadata_edited-on-purpose":"Choose asset metadata edited-on-purpose",
        "Drag_and_drop_an":"Drag and drop an",
        "to_the_Asset_Bucket_to_add_or_use_the":"to the Asset Bucket to add, or use the",
        "file_browser":"file browser",
        "Upload_Details":"Upload Details",
        "View_on_assets_bucket_page":"View on assets bucket page",
        "Your_Asset_Bucket_is_empty.":"Your Asset Bucket is empty.",
        "Yes_remove":"Yes, remove",
        "No_do_not_remove":"No, do not remove",
        "remove":"remove",
        "the_file":"the file",
        "Once_you_remove_it":"Once you remove it",
        "asset_from_this_upload.":"asset from this upload.",
        "this_asset_from_this_upload?":" this asset from this upload?",
        "owner(s)_are_required":"owner(s) are required",
        "This_field_is_required!":"This field is required!",
        "Master_Asset":"Master Asset",
        "Select_Master_Asset":"Select_Master_Asset",
        "Category_Title_Placeholder_Here":"Category Title Placeholder Here",
        "There_is_no_form_response_for_the_category_named":"There is no form response for the category named",
        "Please_save_to_continue":"Please save to continue",
        // ---------------------------------
        
        // --------- Global Search ----------
        "Global_Search":"Global Search",
        // ---------------------------------
        
        // ---------  Notifications ----------
        "Search_assets_by_ID_case_CAD_categories_etc":"Search assets by ID#, case#, CAD#, categories, etc",
        "Notifications":"Notifications",
        "Clear_All":"Clear All",
        // -------------------------
        
        // --------- Constant ----------
        "Deleted":"Deleted",
        "Trash":"Trash",
        "Not_Categorized":"Not Categorized",
        "Approaching_Deletion":"Approaching Deletion",
        "SimpleSearch":"SimpleSearch",
        "AdvanceSearch":"AdvanceSearch",
        "ShortcutSearch":"ShortcutSearch",
        "Unit_ID":"Unit ID",
        "UnCategorized":"UnCategorized",
        // -------------------------
        
        // --------- Data Table ----------
        "Tables_columns_filter":"Tables columns filter",
        "Clear_all_filters":"Clear all filters",
        "Basic":"Basic",
        "Advance":"Advance",
        "Restrictive":"Restrictive",
        "total_users_in_group":"total users in group",
        "":"",


      }
    }
  };