export const resources = {
    // en: {
    //   translation: {
    //     "assets": "en-Assets",
    //     "Show / hide columns": "en-Show / hide columns",
    //     "Close" : "en-Close",
    //     "Reset to default" : "en-Reset to default",
    //     "Customize columns": "en-Customize columns",
    //     "Save and close" : "en-Save and close",
    //     "Save as preset" : "en-Save as preset",
    //     "Actions": "en-Actions",
    //     "ID":"en-ID",
    //     "Asset Thumbnail":"en-Asset Thumbnail",
    //     "Asset Name":"en-Asset Name",
    //     "Asset Type":"en-Asset Type",
    //     "Unit":"en-Unit",
    //     "Categories":"en-Categories",
    //     "Device":"en-Device",
    //     "Station":"en-Station",
    //     "Recorded By":"en-Recorded By",
    //     "Expiry Date":"en-Expiry Date",
    //     "Status":"en-Status",
    //     "":"en-",
    //     "":"en-",
    //     "":"en-",
    //     "":"en-",
    //   }
    // }

    en: {
      translation: {
        // --------- Asset Lister ----------
        "Asset_Lister":"Asset Lister",
        "Login To Getac Enterprise using Getac Authentication":"Login To Getac Enterprise using Getac Authentication",
        "Inspiring statement about Getac / Getac product that is relevant to user":"Inspiring statement about Getac / Getac product that is relevant to user",
        "You are accessing a restricated information system. Your usage may be monitored, recoreded and subject to audit. Unauthorized use of the system is prohibited and may be subject to criminal and/or civil penalities. By using this system and clicking Log In, you consent to your usage being monitored and recorded.":"You are accessing a restricated information system. Your usage may be monitored, recoreded and subject to audit. Unauthorized use of the system is prohibited and may be subject to criminal and/or civil penalities. By using this system and clicking Log In , you consent to your usage being monitored and recorded.",
        "Log_In":"Log In",
        "assetDataTable":"Assets",
        "userGroup_DataTable":"User Groups",
        "Tables_columns_filter":"Tables columns filter",
        "Close":"Close",
        "Reset_to_default":"Reset to default",
        "Clearall_filters":"Clear all filters",
        "Customize_columns":"Customize columns",
        "Save_and_close":"Save and close",
        "Saveas_preset":"Save as preset",
        "Actions":"Actions",
        "ID":"ID",
        "Asset_Thumbnail":"Asset Thumbnail",
        "Asset_ID":"Asset ID",
        "Asset_Type":"Asset Type",
        "Unit":"Unit",
        "Category":"Category",
        "Description":"Description",
        "Retention_Span":"Retention Span",
        "Device":"Device",
        "Station":"Station",
        "Recorded_By":"Recorded By",
        "User_Name":"Username",
        "Captured":"Captured",
        "File_Status":"File Status",
        "Select_All":"Select all",
        "Grouped_Assets":"Grouped Assets",
        "Assign_User":"Assign User",
        "View_Live_Video":"View Live Video",
        "Modify_Retention":"Modify Retention",
        "Share_Asset":"Share Asset",
        "Video_Analysis":"Video Analysis",
        "Audio_Analysis":"Audio Analysis",
        "Audio_Source":"Audio Source",
        "Select_Audio_Source":"Select Audio Source",
        "Submit_For_Analysis":"Submit For Analysis",
        "Add_to_asset_bucket":"Add to asset bucket",
        "Edit_Category_and_Form":"Edit Category and Form",
        "Categorize":"Categorize",
        "Set_as_primary":"Set as Primary",
        "Email":"Email",
        "File":"File",
        "Metadata":"",
        "Evidence_overlaid_video":"Evidence overlaid video",
        "Metadata_overlaid_video":"Metadata overlaid video",
        "Link_asset":"Link asset",
        "Link_to_this_group":"Link to this group",
        "Move_asset":"Move asset",
        "Move_to_this_group":"Move to this group",
        "Restrict_access":"Restrict access",
        "Remove_from_asset_bucket":"Remove from asset bucket",
        "Set_as_primary_asset":"Set as primary asset",
        "Assign_to_case":"Assign to case",
        "TBD":"TBD",
        "Open_in_Getac_AI_tools_App":"Open in Getac AI tools App",
        "Users":"Users",
        "Apply_to_all_assets_in_the_group":"Apply to all assets in the group",
        "(Selected_users_will_replace_all_current_assigned_users)":"(Selected users will replace all current assigned users)",
        "Save":"Save",
        "Cancel":"Cancel",
        "You_are_attempting_to":"You are attempting to",
        "close":"close",
        "the_modal_dialog":"the modal dialog.",
        "If_you_close_the_modal_dialog,":"If you close the modal dialog,",
        "any_changes_you_ve_made_will_not_be_saved.":"any changes you've made will not be saved.",
        "You_will_not_be_able_to_undo_this_action.":"You will not be able to undo this action.",
        "Are_you_sure_you_would_like_to":"Are you sure you would like to",
        "Yes":"Yes",
        "No,_do_not_close":"No, do not close",
        "You_have_saved_the_asset_categorization":"Success: You have saved the asset categorization",
        "We_re_sorry._The_form_was_unable_to_be_saved._Please_retry_or_contact_your_Systems_Administrator":"Error: We're sorry. The form was unable to be saved. Please retry or contact your Systems Administrator",
        "Indicates_required_field":"Indicates required field",
        "Please_enter_the_reason_for_editing_the_form.":"Please enter the reason for editing the form.",
        "Category_form_edit_reason":"Category form edit reason",
        "Editing_the_category_form_requires_a_reason":"Editing the category form requires a reason",
        "Please_confirm":"Please confirm",
        "Please_be_aware_that_by_removing_this_category,_you_are_reducing_the_assets_lifetime_and_the_asset_will_expire":"Please be aware that by removing this category, you are reducing the assets lifetime and the asset will expire",
        "in":"in",
        "Hours.":"Hours.",
        "Please_be_aware_that_by_removing_this_category,_you_are_reducing_the_assets_lifetime_and_the_asset_will_expire_in":"Please be aware that by removing this category, you are reducing the assets lifetime and the asset will expire in",
        "Unclassified_retention_policy_of_station_will_be_applied_on_this_evidence_group.":"Unclassified retention policy of station will be applied on this evidence group.",
        "You_are_attempting_to_remove":"You are attempting to remove",
        "Do_you_want_you_continue_with_removing_the_category?":"Do you want you continue with removing the category?",
        "Yes,_remove-category":"Yes, remove category",
        "No,_do_not_remove_category":"No, do not remove category",
        "category":"category",
        "Category_Title_Placeholder_Here":"Category Title Placeholder Here",
        "Attention":"Attention",
        "There_is_no_form_response_for_the_category_named,":"There is no form response for the category named,",
        "Please_sav_to_continue.":"Please save to continue.",
        "Back":"Back",
        "Required":"Required",
        "Category_Forms":"Category Forms",
        "is_required":"is required",
        "Category_form":"Category form'",
        "Edit_category":"Edit category",
        "Next":"Next",
        "Skip_category_form_and_save":"Skip category form and save",
        "Choose_Category":"Choose Category",
        "From_the_field_below,_select_one_or_more_relevant_category.":"From the field below, select one or more relevant category.",
        "Removing_the_category_requires_a_reason":"Removing the category requires a reason",
        "Please_enter_the_reason_for_removing_the_category.":"Please enter the reason for removing the category.",
        "Category_removal_reason":"Category removal reason",
        "Extend_retention_by_days":"Extend retention by",
        "Extend_retention_Indefinitely":"Extend retention indefinitely",
        "User":"User",
        "Revert_to_original_retention":"Revert to original retention",
        "Retention_Extended":"Retention Extended",
        "Retention_Reverted":"Retention Reverted",
        "Original_Retention:":"Original Retention:",
        "Current_Retention:":"Current_Retention:",
        "Extend":"Extend",
        "Assets":"Assets",
        "Search_assets_by_ID#_case#_CAD#_categories_owners_etc":"Search assets by ID#, case#, CAD#, categories, owners, etc.",
        "Infinite":"Infinite",
        "No_Expiration":"No Expiration",
        "Day(s)":"Day(s)",
        "Hour(s)":"Hour(s)",
        "Share_email_sent_to_recipients":"Share email sent to recipients",
        "Include_Metadata":"Include Metadata",
        "Link_Expiry":"Link Expiry",
        "Viewable_Once":"Viewable Once",
        "Downloadable":"Downloadable",
        "Please_Select":"Please Select",

        "Search_by":"Search by",
        "Date_and_Time":"Date and Time",
        "Add_search_criteria":"Add search criteria",
        "Reset_advanced_search":"Reset advanced search",
        "Advanced_Search":"Advanced Search",
        "day":"day",
        "days":"days",
        "second":"second",
        "Search_Results":"Search Results",
        "next_30_days":"next 30 days",
        "Search_Assets":"Search Assets",
        "Search":"Search",
        "Confirm":"Confirm",
        "Yes_restrict_access" : "Yes, restrict access",
        "No_do_not_restrict_access" : "No, do not restrict access",
        "Are_you_sure_want_to_restrict_access_to_the_selected_asset(s)?":"You are attempting the restrict access to the selected asset(s)?",
        "Access_to_the_selected_asset(s)_will_be_restricted_to_user_groups_with_the_view_locked_asset_permission.":"You are attempting to restrict access to the selected asset(s). Access to the selected asset(s) will be restricted to user groups with the view locked asset permission.",
        "You_are_attempting_to_restrict_access_to_the_selected_asset(s)._Access_to_the_selected_asset(s)_will_be_restricted_to_user_groups_with_the_view_locked_asset_permission.":"You are attempting to restrict access to the selected asset(s). Access to the selected asset(s) will be restricted to user groups with the view locked asset permission.",
        "Are_you_sure_you_want_to_restrict_access_to_the_selected_asset(s)?":"Are you sure you want to restrict access to the selected asset(s)?",
        "Yes,_restrict_access":"Yes, restrict access",
        "No,_do_not_restrict_access":"No, do not restrict access",
        "Delete":"Delete",
        "the":"the",
        "Notes":"Notes",
        "Bookmark":"Bookmark",
        "action":"action",
        "the_dialogue?":"the dialogue?",
        "Form":"Form",
        "Edit":"Edit",
        "Showless":"Showless",
        "Read_More":"Read More",
        "Map":"Map",
        "Bookmarks":"Bookmarks",
        "Success":"Success",
        "Note_Sucessfully_Updated":"Note Sucessfully Updated ",
        "Bookmark_Edited_Sucessfully":"Bookmark Edited Sucessfully ",
        "Bookmark_Deleted_Sucessfully":"Bookmark Deleted Sucessfully ",
        "Note_Deleted_Sucessfully":"Note Deleted Sucessfully ",
        "Search_Bookmark":"Search Bookmark",
        "Search_by_Name_keyword_etc.":"Search by Name, keyword, etc.",
        "Search_Notes":"Search Notes",
        "Asset_Detail":"Asset Detail",
        "Information":"Information",
        "Asset_Metadata_Info": "ASSET METADATA INFO",
        "Audit_Trail":"AUDIT TRAIL",
        "GROUPED_AND_RELATED_ASSETS":"GROUPED AND RELATED ASSETS",
        "Captured_Date":"Captured Date",
        "Owners":"Owners",
        "Unit":"Unit",
        "CheckSum":"CheckSum",
        "Video_Duration":"Video Duration",
        "Size":"Size",
        "Retention":"Retention",
        "Categories":"Categories",
        "Copyright_©_Getac_Video_Solutions_Inc._and_its_subsidiaries._All_rights_reserved._|_Enterprise_Version":"Copyright © Getac Video Solutions, Inc. and its subsidiaries. All rights reserved. | Enterprise Version",
        "is_successfully_set_as_primary_asset":"is successfully set as primary asset",
        "You_are_sure_want_to_make":"You are sure want to make",
        "the_primary_asset?":"the primary asset?",
        "Set_as_primary_asset":"Set as primary asset",
        "Export":"Export",
        "Asset_Assignees_updated":"Asset Assignees updated",
        "The_asset_is_already_locked":"The asset is already locked.",
        "Download_asset(s)":"Download asset(s)",
        "Download_metadata_info":"Download metadata info",
        "Download_audit_trail":"Download audit trail",
        "Select_to_show_a_column_Drag_and_drop_to_recorder.":"Select to show a column. Drag and drop to recorder.",
        "Are_you_sure_want_to_unlock_access_to_the_selected_asset(s)?" : "Are you sure want to unlock access to the selected asset(s)?.",
        "Access_Unlocked" : "Access Unlocked",
        "Access_Restricted" : "Access Restricted",
        "The_asset_is_already_locked." : "The asset(s) is already locked.",
        "The_asset_is_already_unlocked." : "The asset(s) is already unlocked.",
        "We_re_sorry_The_asset_cant_be_locked_Please_retry_or_contact_your_Systems_Administrator" : "We 're sorry. The asset(s) can't be locked. Please retry or contact your Systems Administrator.",
        "We_re_sorry_The_asset_cant_be_unlocked_Please_retry_or_contact_your_Systems_Administrator" : "We 're sorry. The asset(s) can't be unlocked. Please retry or contact your Systems Administrator.",
        "The_asset_are_locked" : "Success: The asset(s) are locked.",
        "The_asset_are_unlocked" : "Success: The asset(s) are unlocked.",
        "Unlock_Access" : "Unlock Access",
        // -------------------------

        // --------- User ----------
        "Send_Activation_Link":"Send Activation Link",
        "Resend_Activation_Link":"Resend Activation Link",
        "Generate":"Generate",
        "Copy":"Copy",
        "Require_user_to_change_password_on_next_login":"Require user to change password on next login",
        "SSID_Password":"SSID Password",
        "Password":"Password",
        "Confirm_Password":"Confirm Password",
        "Generate_Temporary_Password":"Generate Temporary Password",
        "Manually_Set_Password":"Manually Set Password",
        "You_have_created_the_user_account.":"You have created the user account.",
        "You_have_resent_the_activation_link.":"You have resent the activation link.",
        "You_have_updated_the_user_account.":"You have updated the user account.",
        "Please_provide_a_valid_User_name.":"Please provide a valid User name.",
        "User_name_must_contain_atleast_three_characters.":"User name must contain atleast three characters.",
        "User_name_must_not_exceed_128_characters.":"User name must not exceed 128 characters.",
        "Please_provide_a_valid":"Please provide a valid",
        "must_contain_atleast_three_characters.":"must contain atleast three characters.",
        "must_not_exceed_128_characters.":"must not exceed 128 characters.",
        "First_Name":"First Name",
        "First_Name_is_required":"First Name is required",
        "Last_Name":"Last Name",
        "Last_Name_is_required":"Last Name is required",
        "Username_is_required":"Username is required",
        "Email_is_required":"Email is required",
        "Please_provide_a_valid_email_address":"Please provide a valid email address",
        "Password_is_required":"Password is required",
        "Confirm_Password_is_required":"Confirm Password is required",
        "Passwords_are_not_same":"Passwords are not same",
        "(Link_will_be_sent_after_saving_this_form.)":"(Link will be sent after saving this form.)",
        "Please_provide_a_valid_mobile_number.":"Please provide a valid Mobile number.",
        "Number_must_not_exceed_15_characters.":"Number must not exceed 15 characters.",
        "User_group_is_required":"User group is required",
        "Middle_Initial":"Middle Initial",
        "Phone_Number":"Phone Number",
        "Mobile_Number":"Mobile Number",
        "User_Group":"User Group",
        "Deactivation_Date":"Deactivation Date",
        "User_Password_Setup":"User Password Setup",
        "'user_form'":"'user form'",
        "If_you_close_the_form":"If you close the form",
        "the_form?":"the form?",
        "Yes_close":"Yes, close",
        "custom_range":"custom range",
        "No_Status":"No Status",
        "Status":"Status",
        "Last_Login":"Last Login",
        "Groups":"Groups",
        "Create_User":"Create User",
        "Filter":"Filter",
        "Unlock_user_account":"Unlock user account",
        "Yes_unlock_user_account":"Yes, unlock user account",
        "No_do_not_unlock":"No, do not unlock",
        "Deactivate_user_account":"Deactivate user account",
        "Yes_deactivate_user_account":"Yes, deactivate user account",
        "No_do_not_deactivate":"No, do not deactivate",
        "You_have_unlocked_the_user_account.":"You have unlocked the user account.",
        "You_have_deactivated_the_user_account.":"You have deactivated the user account.",
        "Assets_Action_Menu":"Assets Action Menu",
        "the_following_user_account:":"the following user account:",
        "Please_confirm_if_you_would_like_to":"Please confirm if you would like to",
        "this_user_account.":"this user account.",
        "Edit_user":"Edit user",
        "Unlock_account":"Unlock account",
        "Deactivate_account":"Deactivate account",
        "Pin_should_be_numeric_value" : "Pin should be numeric value.",
        "Pin_must_be_4_numbers" : "Pin must be 4 numbers.",
        "Password_should_be_greater_than_six_characters" : "Password should be greater than six characters.",
        "close_out_of_this_screen_with_unsaved_changes." : "close out of this screen with unsaved changes.",
        "If_you_close_this_screen": "If you close this screen",
        "saved_any_changes_will_not_be_saved":"saved any changes will not be saved",
        "any_un-saved_any_changes_will_not_be_saved. You_will_not_be_able_to_undo_this_action.":"any un-saved any changes will not be saved. You will not be able to undo this action.",
        "Would_you_like_to":"Would you like to",
        "this_screen?": "this screen?",
        // ------------------------------

        // --------- User Group----------
        "Group_Name":"Group Name",
        "Total_Users_Assigned":"Total Users Assigned",
        "Create_Group":"Create Group",
        "GROUP_NAME":"GROUP NAME",
        "USERS":"USERS",
        "APPLICATION_PERMISSIONS":"APPLICATION PERMISSIONS",
        "DATA_PERMISSIONS":"DATA PERMISSIONS",
        "User_group_saved_successfully.":"User group saved successfully.",
        "We_re_sorry_The_group_information_users_and_application_permissions_were_unable_to_be_saved__Please_retry_or_contact_your_System_Administrator.":"We're sorry. The group information, users, and application permissions were unable to be saved. Please retry or contact your System Administrator.",
        "We_re_sorry_The_data_permissions_were_unable_to_be_saved._Please_retry+or_contact_your_System_Administrator.":"We're sorry. The data permissions were unable to be saved. Please retry or contact your System Administrator.",
        "'user_group_form'":"'user group form'",
        "Module_Names":"Module Names",
        "Basic_level":"Basic level",
        "Advanced_level":"Advanced level",
        "Restricted_level":"Restricted level",
        "Apply_application_permissions_from":"Apply application permissions from",
        "All":"All",
        "Uncategorized":"Uncategorized",
        "No_Station":"No Station",
        "Permission_Type":"Permission Type",
        "Permission_Value":"Permission Value",
        "Permission_Level":"Permission Level",
        "Add_data_permissions":"+ Add data permissions",
        "Group_name_is_required":"Group name is required",
        "No_Groups":"No Groups",
        "Select_permission_type":"-- Select permission type --",
        "Select_permission_value":"-- Select permission value --",
        "Select_permission_level":"-- Select permission level --",
        // ----------------------------
        
        // --------- Station ----------
        "Address":"Address",
        "Create_Station":"Create Station",
        "Station_deleted":"Station deleted",
        "The_station_cant_be_deleted__please_check_for_dependent_units_and_assets":"The station can't be deleted, please check for dependent units and assets",
        "Delete_station":"Delete station",
        "No":"No",
        "unlock":"unlock",
        "deactivate":"deactivate",
        "delete":"delete",
        "the_following_user_account":"the following user account",
        "You_are_attempting_to_delete_the_station":"You are attempting to delete the station",
        "Are_you_sure_you_would_like_to_delete_the_station?":"Are you sure you would like to delete the station?",
        "Edit_station":"Edit station",
        "View_default_unit_templates":"View default unit templates",
        "Station_Name_is_required":"Station Name is required",
        "Street_Address_is_required":"Street Address is required",
        "Minimum_5_characters_are_allowed.":"Minimum 5 characters are allowed.",
        "Minimum_3_characters_are_allowed.":"Minimum 3 characters are allowed.",
        "Pass_Code_is_required":"Pass Code is required",
        "Street_Address_is_required":"Street Address is required",
        "Only_alphabets_and_digits_are_allowed.":"Only alphabets and digits are allowed.",
        "Only_digits_are_allowed.":"Only digits are allowed.",
        "Success_You_have_saved_the_Station":"Success: You have saved the Station",
        "Station_Name":"Station Name",
        "Name":"Name",
        "Latitude":"Latitude",
        "Longitude":"Longitude",
        "Location":"Location",
        "Map_location":"Map location",
        "Street_Address":"Street Address",
        "Pass_Code":"Pass Code",
        "Registration_Pass_Code":"Registration Pass Code",
        "Station_Settings":"Station Settings",
        "Data_Retention_Policy":"Uncategorized Retention Policy",
        "Retention_Policy_is_required":"Retention Policy is required",
        "Data_Upload_Policy":"Uncategorized Upload Policy",
        "Upload_Policy_is_required":"Upload Policy is required",
        "BlackBox_Retention_Policy":"BlackBox Retention Policy",
        "Blackbox_Retention_Policy_is_required" : "Blackbox Retention Policy is required",
        "SSID":"SSID",
        "Unit_Templates":"Unit Templates",
        "Select_location_on_the_map":"Select location on the map",
        "Save_Location":"Save Location",
        "Phone_Number_is_not_valid!":"Phone Number is not valid!",
        "Phone_Number":"Phone Number",
        "General":"General",
        // -------------------------
        
        // --------- Unit ----------
        "To_Get_ID":"To Get ID",
        "Success_You_have_saved_the_Default_Unit_Template":"Success: You have saved the Default Unit Template",
        "Manage_Default_Unit_Template":"Manage Default Unit Template",
        "Manage_Unit_Configuration":"Manage Unit Configuration",
        "Edit_template":"Edit template",
        "Clone_template":"Clone template",
        "Delete_template":"Delete template",
        "View_Change_Log":"View Change Log",
        "Are_you_sure_you_would_like_to_delete_template?":"Are you sure you would like to delete template?",
        "template":"template",
        "this":"this",
        "No_Version":"No Version",
        "No_type":"No type",
        "Default":"Default",
        "No_Indicator":"No Indicator",
        "Type":"Type",
        "Indicator":"Indicator",
        "Create_Template":"Create Template",
        "Change_Log":"Change Log: ",
        "Changes":"Changes",
        "Log_Time":"Log Time",
        // ---------------------------
        
        // --------- Header ----------
        "Getac_Command":"Getac Command",
        "Getac_Enterprise":"Getac Enterprise",
        "All_Stations":"All Stations",
        "Departments":"Departments",
        "Help":"Help",
        "User_Profile":"User Profile",
        "Logout":"Logout",
        "Home":"Home",
        "Cases":"Cases",
        "Units_&_Devices":"Units & Devices",
        "ALPR":"ALPR",
        "Plate_Captures":"Plate Captures",
        "Live_ALPR":"Live ALPR",
        "Manage_Hot_List":"Manage Hot List",
        "Manage_Hot_List_Data_Source":"Manage Hot List Data Source",
        "Manage_License_Plates":"Manage License Plates",
        "Admin":"Admin",
        "Manage_User_Groups_Permissions":"Manage User Groups & Permissions",
        "Manage_Users":"Manage Users",
        "Manage_Device_Unit_Templates":"Manage Device & Unit Templates",
        "Evidence(Dev)":"Evidence(Dev)",
        "Manage_Station":"Manage Station",
        // ---------------------------------
        
        // --------- Asset buctet ----------
        "An_asset_you_are_attempting_to_add_to_the_asset_bucket_has_already_been_added.":"An asset you are attempting to add to the asset bucket has already been added.",
        "You_have_added_the_selected_assets_to_the_asset_bucket.":"You have added the selected assets to the asset bucket.",
        "assets":"assets",
        "asset":"asset",  
        "removed_the_asset_bucket":"removed the asset bucket",
        "Asset_Bucket_can_be_used_to_build_cases_and_do_one_action_on_many_assets_at_the_same_time.":"Asset Bucket can be used to build cases and do one action on many assets at the same time.",
        "Asset_Bucket":"Asset Bucket",
        "Minimum_3_and_maximum_128_characters_are_allowed":"Minimum 3 and maximum 128 characters are allowed",
        "Only_alphabets_digits_and_,_-_are_allowed._Must_start_with_an_alphabet_only":"Only alphabets, digits and _, - are allowed. Must start with an alphabet only",
        "File(s)_failed_to_upload.":"File(s) failed to upload.",
        "File(s)_uploaded":"File(s) uploaded",
        "Asset_saved":"Asset_saved",
        "File_has_been_removed_successfully":"File has been removed successfully",
        "Your_Asset_Bucket":"Your Asset Bucket",
        "Please_add_metadata_to_finish_saving_your_uploaded_files":"Please add metadata to finish saving your uploaded files",
        "Add_metadata":"Add metadata",
        "Choose_asset_metadata":"Choose asset metadata",
        "Drag_and_drop_an":"Drag and drop an",
        "to_the_Asset_Bucket_to_add_or_use_the":"to the Asset Bucket to add, or use the",
        "file_browser":"file browser",
        "Upload_Details":"Upload Details",
        "View_on_assets_bucket_page":"View on assets bucket page",
        "Your_Asset_Bucket_is_empty.":"Your Asset Bucket is empty.",
        "Yes_remove":"Yes, remove",
        "No_do_not_remove":"No, do not remove",
        "remove":"remove",
        "the_file":"the file",
        "Once_you_remove_it":"Once you remove it",
        "asset_from_this_upload.":"asset from this upload.",
        "this_asset_from_this_upload?":" this asset from this upload?",
        "owner(s)_are_required":"owner(s) are required",
        "This_field_is_required!":"This field is required!",
        "Master_Asset":"Master Asset",
        "Select_Master_Asset":"Select_Master_Asset",
        "Category_Title_Placeholder_Here":"Category Title Placeholder Here",
        "There_is_no_form_response_for_the_category_named":"There is no form response for the category named",
        "Please_save_to_continue":"Please save to continue",
        "Maximum_lenght_is_1024" : "Maximum lenght is 1024",
        // ---------------------------------
        
        // --------- Global Search ----------
        "Global_Search":"Global Search",
        // ---------------------------------
        
        // ---------  Notifications ----------
        "Search_assets_by_ID_case_CAD_categories_etc":"Search assets by ID#, case#, CAD#, categories, etc",
        "Notifications":"Notifications",
        "Clear_All":"Clear All",
        // -------------------------
        
        // --------- Constant ----------
        "Deleted":"Deleted",
        "Trash":"Trash",
        "Not_Categorized":"Not Categorized",
        "Approaching_Deletion":"Approaching Deletion",
        "SimpleSearch":"SimpleSearch",
        "AdvanceSearch":"AdvanceSearch",
        "ShortcutSearch":"ShortcutSearch",
        "Unit_ID":"Unit ID",
        "UnCategorized":"UnCategorized",
        // -------------------------
        
        // --------- Data Table ----------
        "Tables_columns_filter":"Tables columns filter",
        "Clear_all_filters":"Clear all filters",
        "Basic":"Basic",
        "Advance":"Advance",
        "Restrictive":"Restrictive",
        "total_users_in_group":"total users in group",
        "":"",

        // ------ Else ------
        "View":"View",
        "Share":"Share",
        "Update":"Update",
        "Exclusive(All)":"Exclusive(All)",
        "text":"text",
        "password":"password",
        "Hide":"Hide",
        "Show":"Show",


        // ------------------

        "Yes_delete":"Yes, delete",
        "No_do_not_delete":"No, do not delete",

        // -------- Unit N Devices --------
        "Template Name":"Template Name",
        "Camera":"Camera",
        "Mode":"Mode",
        "PC":"PC",
        "DVR":"DVR",
        "Getac Login Mode":"Getac Login Mode",
        "Getac Auth":"Getac Auth",
        "Active Directory":"Active Directory",
        "CAD":"CAD",
        "add all":"add all",
        "Config Update Interval":"Config Update Interval",
        "Media Retention Policy":"Media Retention Policy",
        "none":"none",
        "Maximum Video Length":"Maximum Video Length",
        "GPS Frequency":"GPS Frequency",
        "Reboot":"Reboot",
        "VR-X10":"VR-X10",
        "VR-X20":"VR-X20",
        "USB GPS":"USB GPS",
        "Port Name":"Port Name",
        "Serial Baud Rate":"Serial Baud Rate",
        "Hardware Monitoring When Offline":"Hardware Monitoring When Offline",
        "Recording Stop When Lights On":"Recording Stop When Lights On",
        "Shutdown After Ignition Off":"Shutdown After Ignition Off",
        "Shutdown After Ignition Off When Uploading":"Shutdown After Ignition Off When Uploading",
        "Shutdown On Vehicle Battery Voltage":"Shutdown On Vehicle Battery Voltage",
        "Blackbox Retention Policy":"Blackbox Retention Policy",
        "Beep During Recording":"Beep During Recording",
        "Sensor Recording Start Delay":"Sensor Recording Start Delay",
        "required":"Required",
        "Two High":"Two High",
        "Force Logout On Shutdown":"Force Logout On Shutdown",
        "Logout users on closing/shutdown application":"Logout users on closing/shutdown application",
        "Enable Logout From Unit":"Enable Logout From Unit",
        "Enable logout from the unit. At least one user has to be logged in to the system if disabled":"Enable logout from the unit. At least one user has to be logged in to the system if disabled",
        "Diagnostics Logging Interval":"Diagnostics Logging Interval",
        "(Minimum allowed is 0 and maximum allowed is 10000)":"(Minimum allowed is 0 and maximum allowed is 10000)",
        "Allows to specify logging interval for diagnostic logs":"Allows to specify logging interval for diagnostic logs",
        "Microphone Charge Time":"Microphone Charge Time",
        "USB Port Charge Time":"USB Port Charge Time",
        "FieldArray":"FieldArray",
        "IP Camera":"IP Camera",
        "Video FC(1-8)":"Video FC(1-8)",
        "Discovered devices":"Discovered devices",
        "all":"all",
        "Device Name":"Device Name",
        "Video Profile":"Video Profile",
        "Pre-Recording Duration":"Pre-Recording Duration",
        "(Minimum allowed is 1 and maximum allowed is 1000)":"(Minimum allowed is 1 and maximum allowed is 1000)",
        "Allows to specify the time period for the camera to capture before Start Recording button is pressed":"Allows to specify the time period for the camera to capture before Start Recording button is pressed",
        "Greater than 1000":"Greater than 1000",
        "Less than 1":"Less than 1",
        "Post-Recording Duration":"Post-Recording Duration",
        "Allows to specify the time period for the camera to capture after Stop Recording button is pressed":"Allows to specify the time period for the camera to capture after Stop Recording button is pressed",
        "Off":"Off",
        "Continous":"Continous",
        "(As long as DVR is on, it is recording.)":"(As long as DVR is on, it is recording.)",
        "Only when recording in-car video to in-car disk":"Only when recording in-car video to in-car disk",
        "Blackbox Directory":"Blackbox Directory",
        "Mic Off When Not Recording":"Mic Off When Not Recording",
        "Overlay Metadata On Video":"Overlay Metadata On Video",
        "Includes GPS/Date and time overlays in the video stream":"Includes GPS/Date and time overlays in the video stream",
        "Capture With Master Button":"Capture With Master Button",
        "Start/Stop Capture With Master Button":"Start/Stop Capture With Master Button",
        "Camera Mode":"Camera Mode",
        "Allows to select Camera Mode for the screen on startup":"Allows to select Camera Mode for the screen on startup",
        "Auto":"Auto",
        "Day":"Day",
        "Night":"Night",
        "IR":"IR",
        "Audio Device Type":"Audio Device Type",
        "Allows to select one or several Audio devices for the primary device":"Allows to select one or several Audio devices for the primary device",
        "Veretos Analog":"Veretos Analog",
        "Discovered devices":"Discovered devices",
        "Allows to specify categories for selection after recording":"Allows to specify categories for selection after recording",
        "Enable Categorization":"Enable Categorization",
        "Keeps synchronizing unit configuration at the specified minutes":"Keeps synchronizing unit configuration at the specified minutes",
        "(Minimum allowed is 5 and maximum allowed is 120)":"(Minimum allowed is 5 and maximum allowed is 120)",
        "Allows to specify maximum video chunk to record for continuous video":"Allows to specify maximum video chunk to record for continuous video",
        "(Minimum allowed is 0 and maximum allowed is 3600)":"(Minimum allowed is 0 and maximum allowed is 3600)",
        "Reboot Every Day":"Reboot Every Day",
        "Allows to specify time to reboot the unit":"Allows to specify time to reboot the unit",
        "Enable USB GPS":"Enable USB GPS",
        "Serial or UDP for GPS":"Serial or UDP for GPS",
        "Baud rate for serial port or UDP port for network GPS device":"Baud rate for serial port or UDP port for network GPS device",
        "Hardware Interface":"Hardware Interface",
        "Enable Hardware Monitoring When Offline":"Enable Hardware Monitoring When Offline",
        "Enable Recording Stop When Lights On":"Enable Recording Stop When Lights On",
        "Shutdown the unit after specified number of minutes if the ignition turned off":"Shutdown the unit after specified number of minutes if the ignition turned off",
        "Shutdown the unit after specified number of minutes when unit is uploading if the ignition turned off":"Shutdown the unit after specified number of minutes when unit is uploading if the ignition turned off",
        "Shutdown the unit if the battery voltage is sensed at the specific number":"Shutdown the unit if the battery voltage is sensed at the specific number",
        "Enable Beep":"Enable Beep",
        "Allows to specify interval for the beep during recording":"Allows to specify interval for the beep during recording",
        "(Minimum allowed is 0 and maximum allowed is 60)":"(Minimum allowed is 0 and maximum allowed is 60)",
        "Allows to specify delay for recording to start on hardware event":"Allows to specify delay for recording to start on hardware event",
        "minutes":"minutes",
        "volts":"volts",
        "seconds":"seconds",
        "GPS":"GPS",
        "Device Type":"Device Type",
        "Blackbox Recording":"Blackbox Recording",
        "Add camera":"Add camera",
        "Please_Confirm":"Please Confirm",
        "Remove_camera":"Remove camera",
        "If_you_remove_this_camera,":"If you remove this camera,",
        "this_camera?":"this camera?",
        "CLONE - ":"CLONE - ",
        "Video Resolution":"Video Resolution",
        "Bit Rate":"Bit Rate",
        "High":"High",
        "Low":"Low",
        "Medium":"Medium",
        "Video Cut Size":"Video Cut Size",
        "1 hour":"1 hour",
        "2 hour":"2 hour",
        "3 hour":"3 hour",
        "Video Pre-Buffer":"Video Pre-Buffer",
        "Enable Video Pre-Buffer":"Enable Video Pre-Buffer",
        "10 sec":"10 sec",
        "20 sec":"20 sec",
        "30 sec":"30 sec",
        "60 sec":"60 sec",
        "120 sec":"120 sec",
        "180 sec":"180 sec",
        "240 sec":"240 sec",
        "300 sec":"300 sec",
        "360 sec":"360 sec",
        "420 sec":"420 sec",
        "480 sec":"480 sec",
        "540 sec":"540 sec",
        "600 sec":"600 sec",
        "Mute Audio Pre-Buffer":"Mute Audio Pre-Buffer",
        "Video Overlay":"Video Overlay",
        "Enable Video Overlay":"Enable Video Overlay",
        "Date and Time":"Date and Time",
        "Date ,Time and User":"Date ,Time and User",
        "Unit , Date and Time":"Unit , Date and Time",
        "User , Unit , Date and Time":"User , Unit , Date and Time",
        "Recording Beep Interval":"Recording Beep Interval",
        "Enable Recording Beep":"Enable Recording Beep",
        "Vibration":"Vibration",
        "Recording Vibration":"Recording Vibration",
        "Device Controls":"Device Controls",
        "Add All":"Add All",
        "Category 1":"Category 1",
        "Category 2":"Category 2",
        "Category 3":"Category 3",
        "Category 4":"Category 4",
        "Enabled":"Enabled",
        "Disabled":"Disabled",
        "Always Muted":"Always Muted",
        "(“Always Muted” will disable “Disable Audio Only Recording” checkbox)":"(“Always Muted” will disable “Disable Audio Only Recording” checkbox)",
        "Disable Audio Only Recording":"Disable Audio Only Recording",
        "Bookmark":"Bookmark",
        "Disable Mark":"Disable Mark",
        "Disable Wi-Fi and Bluetooth":"Disable Wi-Fi and Bluetooth",
        "(If selected will disable �Enable GPS� checkbox section)":"(If selected will disable �Enable GPS� checkbox section)",
        "Enable GPS":"Enable GPS",
        "How often BC04 sends heartbeats":"How often BC04 sends heartbeats",
        "How often <Body Worn Type> sends heartbeats":"How often <Body Worn Type> sends heartbeats",
        "GPS Heartbeat":"GPS Heartbeat",
        "(Minimum allowed is 30 and maximum allowed is 3600)":"(Minimum allowed is 30 and maximum allowed is 3600)",
        "Too Low":"Too Low",
        "Too High":"Too High",
        "GPS Heartbeat While Recording":"GPS Heartbeat While Recording",
        "Interval between heartbeats when recording":"Interval between heartbeats when recording",
        "Enable LTE":"Enable LTE",
        "Private APN":"Private APN",
        "APN Name":"APN Name",
        "APN":"APN",
        "Proxy":"Proxy",
        "Port":"Port",
        "User Name":"User Name",
        "Server":"Server",
        "MMSC":"MMSC",
        "MMSC Proxy":"MMSC Proxy",
        "MMSC Port":"MMSC Port",
        "MCC":"MCC",
        "MNC":"MNC",
        "Authentication Type":"Authentication Type",
        "None":"None",
        "PAP":"PAP",
        "CHAP":"CHAP",
        "PAP or CHAP":"PAP or CHAP",
        "APN Type":"APN Type",
        "Default":"Default",
        "SUPL":"SUPL",
        "MMS":"MMS",
        "APN Protocol":"APN Protocol",
        "IP":"IP",
        "IPv4/IPv6":"IPv4/IPv6",
        "APN Roaming Protocol":"APN Roaming Protocol",
        "Template, ":"Template, ",
        "Template_Sucessfully_Saved":"Template Sucessfully Saved",
        "Template_with_this_name":"Template with this name",
        "is_already_exists":"is already exists",
        "Template_Edited_Sucessfully":"Template Edited Sucessfully",
        "BC03_Template":"BC03 Template",
        "Recording":"Recording",
        "Mute":"Mute",
        "categories is required":"categories is required",
        "No_Template":"No Template",
        "Serial_Number":"Serial Number",
        "Version":"Version",
        "Assigned_To":"Assigned To",
        "Last_Checked_In":"Last Checked In",
        "Template":"Template",
        "File_Name":"File Name",
        "Please_provide_a_valid_Unit_Id.":"Please provide a valid Unit Id.",
        "Unit_Id_must_contains_atleast_three_characters.":"Unit Id must contains atleast three characters.",
        "Unit_Id_must_not_exceed_128_characters.":"Unit Id must not exceed 128 characters.",
        "Unit_Id_is_Required":"Unit Id is Required",
        "Unit_Configuration_Template":"Unit Configuration Template",
        "Unit_Detail":"Unit Detail: ",
        "Unit_Edited_Sucessfully":"Unit Edited Sucessfully",
        "Device_Name":"Device Name",
        "Device_Type":"Device Type",
        "Serial_Number":"Serial Number",
        "Configurations":"Configurations",
        "Queued_Assets":"Queued_Assets",
        "ASSIGNED_TO":"ASSIGNED TO",
        "ASSETS":"ASSETS",
        "UPLOADING":"UPLOADING",
        "STATION":"STATION",
        "CURRENT_VERSION":"CURRENT VERSION",
        "SERIAL_NUMBER":"SERIAL NUMBER",
        "STATUS":"STATUS",
        "PRIMARY_UNIT_DEVICE":"PRIMARY UNIT DEVICE",
        "Exit":"Exit",
        "test":"test",
        "UNREGISTERED":"UNREGISTERED",
        "Edit_Configuration":"Edit <Configuration>",
        "Assign_user(s)":"Assign user(s)",
        "Deactivate":"Deactivate",
        "Devices":"Devices",
        "Queued_Assets":"Queued Assets",
        "Units_&_Devices":"Units & Devices",
        //--------------
        "Unit_Details":"Unit Details",
        "'unit_configuration_form'":"'unit configuration form'",
        "Configuration":"Configuration",
        "Events":"Events",
        "Device_Diagnostic":"Device Diagnostic",
        "Update_History":"Update History",
        "Unit Template":"Unit Template",
        "LTE Settings":"LTE Settings",
        "Template Information":"Template Information",
        "Unit Settings":"Unit Settings",
        "Primary Device":"Primary Device",
        "CameraSetup":"CameraSetup",
        "Camera Setup":"Camera Setup",

           // --------- Share Asset ----------
        "Link_Expiration":"Link Expiration",
        "Link_Permissions":"Link Permissions",
        "Comments":"Comments",
        "Reason_for_Sharing":"Reason for Sharing",

      }
    }
  };