export const resources = {
    hr: {
      translation: {
        // --------- Asset Lister ----------
        "Asset_Lister":"hr-Asset Lister",
        "Login To Getac Enterprise using Getac Authentication":"hr-Login To Getac Enterprise using Getac Authentication",
        "Inspiring statement about Getac / Getac product that is relevant to user":"hr-Inspiring statement about Getac / Getac product that is relevant to user",
        "You are accessing a restricated information system. Your usage may be monitored, recoreded and subject to audit. Unauthorized use of the system is prohibited and may be subject to criminal and/or civil penalities. By using this system and clicking Log In, you consent to your usage being monitored and recorded.":"hr-You are accessing a restricated information system. Your usage may be monitored, recoreded and subject to audit. Unauthorized use of the system is prohibited and may be subject to criminal and/or civil penalities. By using this system and clicking Log In , you consent to your usage being monitored and recorded.",
        "Log_In":"hr-Log In",
        "assetDataTable":"hr-Assets",
        "userGroup_DataTable":"hr-User Groups",
        "Tables_columns_filter":"hr-Tables columns filter",
        "Close":"hr-Close",
        "Reset_to_default":"hr-Reset to default",
        "Clearall_filters":"hr-Clear all filters",
        "Customize_columns":"hr-Customize columns",
        "Save_and_close":"hr-Save and close",
        "Saveas_preset":"hr-Save as preset",
        "Actions":"hr-Actions",
        "ID":"hr-ID",
        "Asset_Thumbnail":"hr-Asset Thumbnail",
        "Asset_ID":"hr-Asset ID",
        "Asset_Type":"hr-Asset Type",
        "Unit":"hr-Unit",
        "Category":"hr-Category",
        "Description":"hr-Description",
        "Retention_Span":"hr-Retention Span",
        "Device":"hr-Device",
        "Station":"hr-Station",
        "Recorded_By":"hr-Recorded By",
        "User_Name":"hr-Username",
        "Captured":"hr-Captured",
        "File_Status":"hr-File Status",
        "Select_All":"hr-Select all",
        "Grouped_Assets":"hr-Grouped Assets",
        "Assign_User":"hr-Assign User",
        "Modify_Retention":"hr-Modify Retention",
        "Share_Asset":"hr-Share Asset",
        "Video_Analysis":"hr-Video Analysis",
        "Audio_Analysis":"hrAudio Analysis",
        "Audio_Source":"Audio Source",
        "Select_Audio_Source":"hr-Select Audio Source",
        "Submit_For_Analysis":"hr-Submit For Analysis",
        "Add_to_asset_bucket":"hr-Add to asset bucket",
        "Edit_Category_and_Form":"hr-Edit Category and Form",
        "Categorize":"hr-Categorize",
        "Email":"hr-Email",
        "File":"hr-File",
        "Metadata":"hr-",
        "Evidence_overlaid_video":"hr-Evidence overlaid video",
        "Metadata_overlaid_video":"hr-Metadata overlaid video",
        "Link_asset":"hr-Link asset",
        "Link_to_this_group":"hr-Link to this group",
        "Move_asset":"hr-Move asset",
        "Move_to_this_group":"hr-Move to this group",
        "Restrict_access":"hr-Restrict access",
        "Remove_from_asset_bucket":"hr-Remove from asset bucket",
        "Set_as_primary_asset":"hr-Set as primary asset",
        "Assign_to_case":"hr-Assign to case",
        "TBD":"hr-TBD",
        "Open_in_Getac_AI_tools_App":"hr-Open in Getac AI tools App",
        "Users":"hr-Users",
        "Apply_to_all_assets_in_the_group":"hr-Apply to all assets in the group",
        "(Selected_users_will_replace_all_current_assigned_users)":"(hr-Selected users will replace all current assigned users)",
        "Save":"hr-Save",
        "Cancel":"hr-Cancel",
        "You_are_attempting_to":"hr-You are attempting to",
        "close":"hr-close",
        "the_modal_dialog":"hr-the modal dialog.",
        "If_you_close_the_modal_dialog,":"hr-If you close the modal dialog,",
        "any_changes_you_ve_made_will_not_be_saved.":"hr-any changes you've made will not be saved.",
        "You_will_not_be_able_to_undo_this_action.":"hr-You will not be able to undo this action.",
        "Are_you_sure_you_would_like_to":"hr-Are you sure you would like to",
        "Yes":"hr-Yes",
        "No,_do_not_close":"hr-No, do not close",
        "Success:_You_have_saved_the_asset_categorization":"hr-Success: You have saved the asset categorization",
        "Error_We_re_sorry._The_form_was_unable_to_be_saved._Please_retry_or_contact_your_Systems_Administrator":"hr-Error: We're sorry. The form was unable to be saved. Please retry or contact your Systems Administrator",
        "Indicates_required_field":"hr-Indicates required field",
        "Please_enter_the_reason_for_editing_the_form.":"hr-Please enter the reason for editing the form.",
        "Category_form_edit_reason":"hr-Category form edit reason",
        "Editing_the_category_form_requires_a_reason":"hr-Editing the category form requires a reason",
        "Please_confirm":"hr-Please confirm",
        "Please_be_aware_that_by_removing_this_category,_you_are_reducing_the_assets_lifetime_and_the_asset_will_expire":"hr-Please be aware that by removing this category, you are reducing the assets lifetime and the asset will expire",
        "in":"hr-in",
        "Hours.":"hr-Hours.",
        "Please_be_aware_that_by_removing_this_category,_you_are_reducing_the_assets_lifetime_and_the_asset_will_expire_in":"hr-Please be aware that by removing this category, you are reducing the assets lifetime and the asset will expire in",
        "Unclassified_retention_policy_of_station_will_be_applied_on_this_evidence_group.":"hr-Unclassified retention policy of station will be applied on this evidence group.",
        "Success_You_have_saved_the_asset_categorization":"hr-Success: You have saved the asset categorization",
        "We_re_sorry._The_form_was_unable_to_be_saved._Please_retry_or_contact_your_Systems_Administrator":"hr-We 're sorry. The form was unable to be saved. Please retry or contact your Systems Administrator",
        "You_are_attempting_to_remove":"hr-You are attempting to remove",
        "Do_you_want_you_continue_with_removing_the_category?":"hr-Do you want you continue with removing the category?",
        "Yes,_remove-category":"hr-Yes, remove category",
        "No,_do_not_remove_category":"hr-No, do not remove category",
        "category":"hr-category",
        "Category_Title_Placeholder_Here":"hr-Category Title Placeholder Here",
        "Attention":"hr-Attention",
        "There_is_no_form_response_for_the_category_named,":"hr-There is no form response for the category named,",
        "Please_sav_to_continue.":"hr-Please save to continue.",
        "Back":"hr-Back",
        "Required":"hr-Required",
        "Category_Forms":"hr-Category Forms",
        "is_required":"hr-is required",
        "Category_form":"hr-Category form'",
        "Edit_category":"hr-Edit category",
        "Next":"hr-Next",
        "Skip_category_form_and_save":"hr-Skip category form and save",
        "Choose_Category":"hr-Choose Category",
        "From_the_field_below,_select_one_or_more_relevant_category.":"hr-From the field below, select one or more relevant category.",
        "Removing_the_category_requires_a_reason":"hr-Removing the category requires a reason",
        "Please_enter_the_reason_for_removing_the_category.":"hr-Please enter the reason for removing the category.",
        "Category_removal_reason":"hr-Category removal reason",
        "Extend_retention_by_days":"hr-Extend retention by days",
        "Extend_retention_Indefinitely":"hr-Extend retention Indefinitely",
        "User":"hr-User",
        "Revert_to_original_retention":"hr-Revert to original retention",
        "Retention_Extended":"hr-Retention Extended",
        "Retention_Reverted":"hr-Retention Reverted",
        "Original_Retention:":"hr-Original Retention:",
        "Current_Retention:":"hr-Current_Retention:",
        "Extend":"hr-Extend",
        "Assets":"hr-Assets",
        "Search_assets_by_ID#_case#_CAD#_categories_owners_etc":"hr-Search assets by ID#, case#, CAD#, categories, owners etc.",
        "Infinite":"hr-Infinite",
        "No_Expiration":"hr-No Expiration",
        "Day(s)":"hr-Day(s)",
        "Hour(s)":"hr-Hour(s)",
        "Share_email_sent_to_recipients":"hr-Share email sent to recipients",
        "Include_Metadata":"hr-Include Metadata",
        "Link_Expiry":"hr-Link Expiry",
        "Viewable_Once":"hr-Viewable Once",
        "Downloadable":"hr-Downloadable",
        "Please_Select":"hr-Please Select",
        "Search_by":"hr-Search by",
        "Date_and_Time":"hr-Date and Time",
        "Add_search_criteria":"hr-Add search criteria",
        "Reset_advanced_search":"hr-Reset advanced search",
        "Advanced_Search":"hr-Advanced Search",
        "day":"hr-day",
        "days":"hr-days",
        "second":"hr-second",
        "Search_Results":"hr-Search Results",
        "next_30_days":"hr-next 30 days",
        "Search_Assets":"hr-Search Assets",
        "Search":"hr-Search",
        "Confirm":"hr-Confirm",
        "Are_you_sure_want_to_restrict_access_to_the_selected_asset(s)?":"hr-Are you sure want to restrict access to the selected asset(s)?",
        "Access_to_the_selected_asset(s)_will_be_restricted_to_user_groups_with_the_view_locked_asset_permission.":"hr-Access to the selected asset(s) will be restricted to user groups with the view locked asset permission.",
        "Delete":"hr-Delete",
        "the":"hr-the",
        "Notes":"hr-Notes",
        "Bookmark":"hr-Bookmark",
        "action":"hr-action",
        "the_dialogue?":"hr-the dialogue?",
        "Form":"hr-Form",
        "Edit":"hr-Edit",
        "Showless":"hr-Showless",
        "Read_More":"hr-Read More",
        "Map":"hr-Map",
        "Bookmarks":"hr-Bookmarks",
        "Success":"hr-Success",
        "Note_Sucessfully_Updated":"hr-Note Sucessfully Updated ",
        "Bookmark_Edited_Sucessfully":"hr-Bookmark Edited Sucessfully ",
        "Bookmark_Deleted_Sucessfully":"hr-Bookmark Deleted Sucessfully ",
        "Note_Deleted_Sucessfully":"hr-Note Deleted Sucessfully ",
        "Search_Bookmark":"hr-Search Bookmark",
        "Search_by_Name_keyword_etc.":"hr-Search by Name, keyword, etc.",
        "Search_Notes":"hr-Search Notes",
        "Asset_Detail:_":"hr-Asset Detail: ",
        "Information":"hr-Information",
        "GROUPED_AND_RELATED_ASSETS":"hr-GROUPED AND RELATED ASSETS",
        "Captured_Date":"hr-Captured Date",
        "Owners":"hr-Owners",
        "Unit":"hr-Unit",
        "CheckSum":"hr-CheckSum",
        "Video_Duration":"hr-Video Duration",
        "Size":"hr-Size",
        "Retention":"hr-Retention",
        "Categories":"hr-Categories",
        "Copyright_©_Getac_Video_Solutions_Inc._and_its_subsidiaries._All_rights_reserved._|_Enterprise_Version":"hr-Copyright © Getac Video Solutions, Inc. and its subsidiaries. All rights reserved. | Enterprise Version",
        "is_successfully_set_as_primary_asset":"hr-is successfully set as primary asset",
        "You_are_sure_want_to_make":"hr-You are sure want to make",
        "the_primary_asset?":"hr-the primary asset?",
        "Set_as_primary_asset":"hr-Set as primary asset",
        "Export":"hr-Export",
        "Asset_Assignees_updated":"hr-Asset Assignees updated",
        "The_asset_is_already_locked":"hr-The asset is already locked.",
        "Download_asset(s)":"hr-Download asset(s)",
        "Download_metadata_info":"hr-Download metadata info",
        "Download_audit_trail":"hr-Download audit trail",
        "Select_to_show_a_column_Drag_and_drop_to_recorder.":"hr-Select to show a column. Drag and drop to recorder.",
        // -------------------------

        // --------- User ----------
        "Send_Activation_Link":"hr-Send Activation Link",
        "Resend_Activation_Link":"hr-Resend Activation Link",
        "Generate":"hr-Generate",
        "Copy":"hr-Copy",
        "Require_user_to_change_password_on_next_login":"hr-Require user to change password on next login",
        "Password":"hr-Password",
        "Confirm_Password":"hr-Confirm Password",
        "Generate_Temporary_Password":"hr-Generate Temporary Password",
        "Manually_Set_Password":"hr-Manually Set Password",
        "You_have_created_the_user_account.":"hr-You have created the user account.",
        "You_have_resent_the_activation_link.":"hr-You have resent the activation link.",
        "You_have_updated_the_user_account.":"hr-You have updated the user account.",
        "Please_provide_a_valid_User_name.":"hr-Please provide a valid User name.",
        "User_name_must_contain_atleast_three_characters.":"hr-User name must contain atleast three characters.",
        "User_name_must_not_exceed_128_characters.":"hr-User name must not exceed 128 characters.",
        "Please_provide_a_valid":"hr-Please provide a valid",
        "must_contain_atleast_three_characters.":"hr-must contain atleast three characters.",
        "must_not_exceed_128_characters.":"hr-must not exceed 128 characters.",
        "First_Name":"hr-First Name",
        "First_Name_is_required":"hr-First Name is required",
        "Last_Name":"hr-Last Name",
        "Last_Name_is_required":"hr-Last Name is required",
        "Username_is_required":"hr-Username is required",
        "Email_is_required":"hr-Email is required",
        "Please_provide_a_valid_email_address":"hr-Please provide a valid email address",
        "Password_is_required":"hr-Password is required",
        "Confirm_Password_is_required":"hr-Confirm Password is required",
        "Passwords_are_not_same":"hr-Passwords are not same",
        "(Link_will_be_sent_after_saving_this_form.)":"hr-(Link will be sent after saving this form.)",
        "Please_provide_a_valid_phone_number.":"hr-Please provide a valid phone number.",
        "Number_must_not_exceed_15_characters.":"hr-Number must not exceed 15 characters.",
        "User_group_is_required":"hr-User group is required",
        "Middle_Initial":"hr-Middle Initial",
        "Phone_Number":"hr-Phone Number",
        "User_Group":"hr-User Group",
        "Deactivation_Date":"hr-Deactivation Date",
        "User_Password_Setup":"hr-User Password Setup",
        "'user_form'":"hr-'user form'",
        "If_you_close_the_form":"hr-If you close the form",
        "the_form?":"hr-the form?",
        "Yes_close":"hr-Yes, close",
        "custom_range":"hr-custom range",
        "No_Status":"hr-No Status",
        "Status":"hr-Status",
        "Last_Login":"hr-Last Login",
        "Groups":"hr-Groups",
        "Create_User":"hr-Create User",
        "Filter":"hr-Filter",
        "Unlock_user_account":"hr-Unlock user account",
        "Yes_unlock_user_account":"hr-Yes, unlock user account",
        "No_do_not_unlock":"hr-No, do not unlock",
        "Deactivate_user_account":"hr-Deactivate user account",
        "Yes_deactivate_user_account":"hr-Yes, deactivate user account",
        "No_do_not_deactivate":"hr-No, do not deactivate",
        "You_have_unlocked_the_user_account.":"hr-You have unlocked the user account.",
        "You_have_deactivated_the_user_account.":"hr-You have deactivated the user account.",
        "Assets_Action_Menu":"hr-Assets Action Menu",
        "the_following_user_account:":"hr-the following user account:",
        "Please_confirm_if_you_would_like_to":"hr-Please confirm if you would like to",
        "this_user_account.":"hr-this user account.",
        "Edit_user":"hr-Edit user",
        "Unlock_account":"hr-Unlock account",
        "Deactivate_account":"hr-Deactivate account",
        "Pin_should_be_numeric_value" : "hr-Pin should be numeric value.",
        "Pin_must_be_4_numbers" : "hr-Pin must be 4 numbers.",
        "Password_should_be_greater_than_six_characters" : "hr-Password should be greater than six characters.",
        "close_out_of_this_screen_with_unsaved_changes." : "hr-close out of this screen with unsaved changes.",
        "If_you_close_this_screen": "hr-If you close this screen",
        "saved_any_changes_will_not_be_saved":"hr-saved any changes will not be saved",
        "any_un-saved_any_changes_will_not_be_saved. You_will_not_be_able_to_undo_this_action.":"hr-any un-saved any changes will not be saved. You will not be able to undo this action.",
        "Would_you_like_to":"hr-Would you like to",
        "this_screen?": "hr-this screen?",
        // ------------------------------

        // --------- User Group----------
        "Group_Name":"hr-Group Name",
        "Total_Users_Assigned":"hr-Total Users Assigned",
        "Create_Group":"hr-Create Group",
        "GROUP_NAME":"hr-GROUP NAME",
        "USERS":"hr-USERS",
        "APPLICATION_PERMISSIONS":"hr-APPLICATION PERMISSIONS",
        "DATA_PERMISSIONS":"hr-DATA PERMISSIONS",
        "User_group_saved_successfully.":"hr-User group saved successfully.",
        "We_re_sorry_The_group_information_users_and_application_permissions_were_unable_to_be_saved__Please_retry_or_contact_your_System_Administrator.":"hr-We're sorry. The group information, users, and application permissions were unable to be saved. Please retry or contact your System Administrator.",
        "We_re_sorry_The_data_permissions_were_unable_to_be_saved._Please_retry+or_contact_your_System_Administrator.":"hr-We're sorry. The data permissions were unable to be saved. Please retry or contact your System Administrator.",
        "'user_group_form'":"hr-'user group form'",
        "Module_Names":"hr-Module Names",
        "Basic_level":"hr-Basic level",
        "Advanced_level":"hr-Advanced level",
        "Restricted_level":"hr-Restricted level",
        "Apply_application_permissions_from":"hr-Apply application permissions from",
        "All":"hr-All",
        "Uncategorized":"hr-Uncategorized",
        "No_Station":"hr-No Station",
        "Permission_Type":"hr-Permission Type",
        "Permission_Value":"hr-Permission Value",
        "Permission_Level":"hr-Permission Level",
        "Add_data_permissions":"hr-+ Add data permissions",
        "Group_name_is_required":"hr-Group name is required",
        "No_Groups":"hr-No Groups",
        "Select_permission_type":"-- hr-Select permission type --",
        "Select_permission_value":"-- hr-Select permission value --",
        "Select_permission_level":"-- hr-Select permission level --",
        // ----------------------------
        
        // --------- Station ----------
        "Address":"hr-Address",
        "Create_Station":"hr-Create Station",
        "Station_deleted":"hr-Station deleted",
        "The_station_cant_be_deleted__please_check_for_dependent_units_and_assets":"hr-The station can't be deleted, please check for dependent units and assets",
        "Delete_station":"hr-Delete station",
        "No":"hr-No",
        "unlock":"hr-unlock",
        "deactivate":"hr-deactivate",
        "delete":"hr-delete",
        "the_following_user_account":"hr-the following user account",
        "You_are_attempting_to_delete_the_station":"hr-You are attempting to delete the station",
        "Are_you_sure_you_would_like_to_delete_the_station?":"hr-Are you sure you would like to delete the station?",
        "Edit_station":"hr-Edit station",
        "View_default_unit_templates":"hr-View default unit templates",
        "Station_Name_is_required":"hr-Station Name is required",
        "Minimum_5_characters_are_allowed.":"hr-Minimum 5 characters are allowed.",
        "Pass_Code_is_required":"hr-Pass Code is required",
        "Only_alphabets_and_digits_are_allowed.":"hr-Only alphabets and digits are allowed.",
        "Success_You_have_saved_the_Station":"hr-Success: You have saved the Station",
        "Station_Name":"hr-Station Name",
        "Name":"hr-Name",
        "Latitude":"hr-Latitude",
        "Longitude":"hr-Longitude",
        "Location":"hr-Location",
        "Map_location":"hr-Map location",
        "Street_Address":"hr-Street Address",
        "Pass_Code":"hr-Pass Code",
        "Station_Settings":"hr-Station Settings",
        "Data_Retention_Policy":"hr-Data Retention Policy",
        "Retention_Policy_is_required":"hr-Retention Policy is required",
        "Data_Upload_Policy":"hr-Data Upload Policy",
        "Upload_Policy_is_required":"hr-Upload Policy is required",
        "BlackBox_Retention_Policy":"hr-BlackBox Retention Policy",
        "SSID":"hr-SSID",
        "Unit_Templates":"hr-Unit Templates",
        "Select_location_on_the_map":"hr-Select location on the map",
        "Save_Location":"hr-Save Location",
        "Phone_Number_is_not_valid!":"hr-Phone Number is not valid!",
        "Phone_Number":"hr-Phone Number",
        "General":"hr-General",
        // -------------------------
        
        // --------- Unit ----------
        "To_Get_ID":"hr-To Get ID",
        "Success_You_have_saved_the_Default_Unit_Template":"hr-Success: You have saved the Default Unit Template",
        "Manage_Default_Unit_Template":"hr-Manage Default Unit Template",
        "Manage_Unit_Configuration":"hr-Manage Unit Configuration",
        "Edit_template":"hr-Edit template",
        "Clone_template":"hr-Clone template",
        "Delete_template":"hr-Delete template",
        "View_Change_Log":"hr-View Change Log",
        "Are_you_sure_you_would_like_to_delete_template?":"hr-Are you sure you would like to delete template?",
        "template":"hr-template",
        "this":"hr-this",
        "No_Version":"hr-No Version",
        "No_type":"hr-No type",
        "Default":"hr-Default",
        "No_Indicator":"hr-No Indicator",
        "Type":"hr-Type",
        "Indicator":"hr-Indicator",
        "Create_Template":"hr-Create Template",
        "Change_Log":"hr-Change Log: ",
        "Changes":"hr-Changes",
        "Log_Time":"hr-Log Time",
        // ---------------------------
        
        // --------- Header ----------
        "Getac_Command":"hr-Getac Command",
        "Getac_Enterprise":"hr-Getac Enterprise",
        "All_Stations":"hr-All Stations",
        "Departments":"hr-Departments",
        "Help":"hr-Help",
        "User_Profile":"hr-User Profile",
        "Logout":"hr-Logout",
        "Home":"hr-Home",
        "Cases":"hr-Cases",
        "Units_&_Devices":"hr-Units & Devices",
        "ALPR":"hr-ALPR",
        "Plate_Captures":"hr-Plate Captures",
        "Live_ALPR":"hr-Live ALPR",
        "Manage_Hot_List":"hr-Manage Hot List",
        "Manage_Hot_List_Data_Source":"hr-Manage Hot List Data Source",
        "Manage_License_Plates":"hr-Manage License Plates",
        "Admin":"hr-Admin",
        "Manage_User_Groups_Permissions":"hr-Manage User Groups & Permissions",
        "Manage_Users":"hr-Manage Users",
        "Manage_Device_Unit_Templates":"hr-Manage Device & Unit Templates",
        "Evidence(Dev)":"hr-Evidence(Dev)",
        "Manage_Station":"hr-Manage Station",
        // ---------------------------------
        
        // --------- Asset buctet ----------
        "An_asset_you_are_attempting_to_add_to_the_asset_bucket_has_already_been_added.":"hr-An asset you are attempting to add to the asset bucket has already been added.",
        "You_have_added_the_selected_assets_to_the_asset_bucket.":"hr-You have added the selected assets to the asset bucket.",
        "assets":"hr-assets",
        "asset":"hr-asset",  
        "removed_the_asset_bucket":"hr-removed the asset bucket",
        "Asset_Bucket_can_be_used_to_build_cases_and_do_one_action_on_many_assets_at_the_same_time.":"hr-Asset Bucket can be used to build cases and do one action on many assets at the same time.",
        "Asset_Bucket":"hr-Asset Bucket",
        "Minimum_3_and_maximum_128_characters_are_allowed":"hr-Minimum 3 and maximum 128 characters are allowed",
        "Only_alphabets_digits_and_,_-_are_allowed._Must_start_with_an_alphabet_only":"hr-Only alphabets, digits and _, - are allowed. Must start with an alphabet only",
        "File(s)_failed_to_upload.":"hr-File(s) failed to upload.",
        "File(s)_uploaded":"hr-File(s) uploaded",
        "Asset_saved":"hr-Asset_saved",
        "File_has_been_removed_successfully":"hr-File has been removed successfully",
        "Your_Asset_Bucket":"hr-Your Asset Bucket",
        "Please_add_metadata_to_finish_saving_your_uploaded_files":"hr-Please add metadata to finish saving your uploaded files",
        "Add_metadata":"hr-Add metadata",
        "Choose_asset_metadata":"hr-Choose asset metadata",
        "Drag_and_drop_an":"hr-Drag and drop an",
        "to_the_Asset_Bucket_to_add_or_use_the":"hr-to the Asset Bucket to add, or use the",
        "file_browser":"hr-file browser",
        "Upload_Details":"hr-Upload Details",
        "View_on_assets_bucket_page":"hr-View on assets bucket page",
        "Your_Asset_Bucket_is_empty.":"hr-Your Asset Bucket is empty.",
        "Yes_remove":"hr-Yes, remove",
        "No_do_not_remove":"hr-No, do not remove",
        "remove":"hr-remove",
        "the_file":"hr-the file",
        "Once_you_remove_it":"hr-Once you remove it",
        "asset_from_this_upload.":"hr-asset from this upload.",
        "this_asset_from_this_upload?":"hr- this asset from this upload?",
        "owner(s)_are_required":"hr-owner(s) are required",
        "This_field_is_required!":"hr-This field is required!",
        "Master_Asset":"hr-Master Asset",
        "Select_Master_Asset":"hr-Select_Master_Asset",
        "Category_Title_Placeholder_Here":"hr-Category Title Placeholder Here",
        "There_is_no_form_response_for_the_category_named":"hr-There is no form response for the category named",
        "Please_save_to_continue":"hr-Please save to continue",
        // ---------------------------------
        
        // --------- Global Search ----------
        "Global_Search":"hr-Global Search",
        // ---------------------------------
        
        // ---------  Notifications ----------
        "Search_assets_by_ID_case_CAD_categories_etc":"hr-Search assets by ID#, case#, CAD#, categories, etc",
        "Notifications":"hr-Notifications",
        "Clear_All":"hr-Clear All",
        // -------------------------
        
        // --------- Constant ----------
        "Deleted":"hr-Deleted",
        "Trash":"hr-Trash",
        "Not_Categorized":"hr-Not Categorized",
        "Approaching_Deletion":"hr-Approaching Deletion",
        "SimpleSearch":"hr-SimpleSearch",
        "AdvanceSearch":"hr-AdvanceSearch",
        "ShortcutSearch":"hr-ShortcutSearch",
        "Unit_ID":"hr-Unit ID",
        "UnCategorized":"hr-UnCategorized",
        // -------------------------
        
        // --------- Data Table ----------
        "Tables_columns_filter":"hr-Tables columns filter",
        "Clear_all_filters":"hr-Clear all filters",
        "Basic":"hr-Basic",
        "Advance":"hr-Advance",
        "Restrictive":"hr-Restrictive",
        "total_users_in_group":"hr-total users in group",
        
        
        // ------ Else ------
        "View":"hr-View",
        "Share":"hr-Share",
        "Update":"hr-Update",
        "Exclusive(All)":"hr-Exclusive(All)",
        "text":"hr-text",
        "password":"hr-password",
        "Hide":"hr-Hide",
        "Show":"hr-Show",


        // ------------------

        "Yes_delete":"hr-Yes, delete",
        "No_do_not_delete":"hr-No, do not delete",

        // -------- Unit N Devices --------
        "Template Name":"hr-Template Name",
        "Camera":"hr-Camera",
        "Mode":"hr-Mode",
        "PC":"hr-PC",
        "DVR":"hr-DVR",
        "Getac Login Mode":"hr-Getac Login Mode",
        "Getac Auth":"hr-Getac Auth",
        "Active Directory":"hr-Active Directory",
        "CAD":"hr-CAD",
        "add all":"hr-add all",
        "Config Update Interval":"hr-Config Update Interval",
        "Media Retention Policy":"hr-Media Retention Policy",
        "none":"hr-none",
        "Maximum Video Length":"hr-Maximum Video Length",
        "GPS Frequency":"hr-GPS Frequency",
        "Reboot":"hr-Reboot",
        "VR-X10":"hr-VR-X10",
        "VR-X20":"hr-VR-X20",
        "USB GPS":"hr-USB GPS",
        "Port Name":"hr-Port Name",
        "Serial Baud Rate":"hr-Serial Baud Rate",
        "Hardware Monitoring When Offline":"hr-Hardware Monitoring When Offline",
        "Recording Stop When Lights On":"hr-Recording Stop When Lights On",
        "Shutdown After Ignition Off":"hr-Shutdown After Ignition Off",
        "Shutdown After Ignition Off When Uploading":"hr-Shutdown After Ignition Off When Uploading",
        "Shutdown On Vehicle Battery Voltage":"hr-Shutdown On Vehicle Battery Voltage",
        "Blackbox Retention Policy":"hr-Blackbox Retention Policy",
        "Beep During Recording":"hr-Beep During Recording",
        "Sensor Recording Start Delay":"hr-Sensor Recording Start Delay",
        "required":"hr-required",
        "Two High":"hr-Two High",
        "Force Logout On Shutdown":"hr-Force Logout On Shutdown",
        "Logout users on closing/shutdown application":"hr-Logout users on closing/shutdown application",
        "Enable Logout From Unit":"hr-Enable Logout From Unit",
        "Enable logout from the unit. At least one user has to be logged in to the system if disabled":"hr-Enable logout from the unit. At least one user has to be logged in to the system if disabled",
        "Diagnostics Logging Interval":"hr-Diagnostics Logging Interval",
        "(Minimum allowed is 0 and maximum allowed is 10000)":"hr-(Minimum allowed is 0 and maximum allowed is 10000)",
        "Allows to specify logging interval for diagnostic logs":"hr-Allows to specify logging interval for diagnostic logs",
        "Microphone Charge Time":"hr-Microphone Charge Time",
        "USB Port Charge Time":"hr-USB Port Charge Time",
        "FieldArray":"hr-FieldArray",
        "IP Camera":"hr-IP Camera",
        "Video FC(1-8)":"hr-Video FC(1-8)",
        "Discovered devices":"hr-Discovered devices",
        "all":"hr-all",
        "Device Name":"hr-Device Name",
        "Video Profile":"hr-Video Profile",
        "Pre-Recording Duration":"hr-Pre-Recording Duration",
        "(Minimum allowed is 1 and maximum allowed is 1000)":"hr-(Minimum allowed is 1 and maximum allowed is 1000)",
        "Allows to specify the time period for the camera to capture before Start Recording button is pressed":"hr-Allows to specify the time period for the camera to capture before Start Recording button is pressed",
        "Greater than 1000":"hr-Greater than 1000",
        "Less than 1":"hr-Less than 1",
        "Post-Recording Duration":"hr-Post-Recording Duration",
        "Allows to specify the time period for the camera to capture after Stop Recording button is pressed":"hr-Allows to specify the time period for the camera to capture after Stop Recording button is pressed",
        "Off":"hr-Off",
        "Continous":"hr-Continous",
        "(As long as DVR is on, it is recording.)":"hr-(As long as DVR is on, it is recording.)",
        "Only when recording in-car video to in-car disk":"hr-Only when recording in-car video to in-car disk",
        "Blackbox Directory":"hr-Blackbox Directory",
        "Mic Off When Not Recording":"hr-Mic Off When Not Recording",
        "Overlay Metadata On Video":"hr-Overlay Metadata On Video",
        "Includes GPS/Date and time overlays in the video stream":"hr-Includes GPS/Date and time overlays in the video stream",
        "Capture With Master Button":"hr-Capture With Master Button",
        "Start/Stop Capture With Master Button":"hr-Start/Stop Capture With Master Button",
        "Camera Mode":"hr-Camera Mode",
        "Allows to select Camera Mode for the screen on startup":"hr-Allows to select Camera Mode for the screen on startup",
        "Auto":"hr-Auto",
        "Day":"hr-Day",
        "Night":"hr-Night",
        "IR":"hr-IR",
        "Audio Device Type":"hr-Audio Device Type",
        "Allows to select one or several Audio devices for the primary device":"hr-Allows to select one or several Audio devices for the primary device",
        "Veretos Analog":"hr-Veretos Analog",
        "Discovered devices":"hr-Discovered devices",
        "Allows to specify categories for selection after recording":"hr-Allows to specify categories for selection after recording",
        "Enable Categorization":"hr-Enable Categorization",
        "Keeps synchronizing unit configuration at the specified minutes":"hr-Keeps synchronizing unit configuration at the specified minutes",
        "(Minimum allowed is 5 and maximum allowed is 120)":"hr-(Minimum allowed is 5 and maximum allowed is 120)",
        "Allows to specify maximum video chunk to record for continuous video":"hr-Allows to specify maximum video chunk to record for continuous video",
        "(Minimum allowed is 0 and maximum allowed is 3600)":"hr-(Minimum allowed is 0 and maximum allowed is 3600)",
        "Reboot Every Day":"hr-Reboot Every Day",
        "Allows to specify time to reboot the unit":"hr-Allows to specify time to reboot the unit",
        "Enable USB GPS":"hr-Enable USB GPS",
        "Serial or UDP for GPS":"hr-Serial or UDP for GPS",
        "Baud rate for serial port or UDP port for network GPS device":"hr-Baud rate for serial port or UDP port for network GPS device",
        "Hardware Interface":"hr-Hardware Interface",
        "Enable Hardware Monitoring When Offline":"hr-Enable Hardware Monitoring When Offline",
        "Enable Recording Stop When Lights On":"hr-Enable Recording Stop When Lights On",
        "Shutdown the unit after specified number of minutes if the ignition turned off":"hr-Shutdown the unit after specified number of minutes if the ignition turned off",
        "Shutdown the unit after specified number of minutes when unit is uploading if the ignition turned off":"hr-Shutdown the unit after specified number of minutes when unit is uploading if the ignition turned off",
        "Shutdown the unit if the battery voltage is sensed at the specific number":"hr-Shutdown the unit if the battery voltage is sensed at the specific number",
        "Enable Beep":"hr-Enable Beep",
        "Allows to specify interval for the beep during recording":"hr-Allows to specify interval for the beep during recording",
        "(Minimum allowed is 0 and maximum allowed is 60)":"hr-(Minimum allowed is 0 and maximum allowed is 60)",
        "Allows to specify delay for recording to start on hardware event":"hr-Allows to specify delay for recording to start on hardware event",
        "minutes":"hr-minutes",
        "volts":"hr-volts",
        "seconds":"hr-seconds",
        "GPS":"hr-GPS",
        "Device Type":"hr-Device Type",
        "Blackbox Recording":"hr-Blackbox Recording",
        "Add camera":"hr-Add camera",
        "Please_Confirm":"hr-Please Confirm",
        "Remove_camera":"hr-Remove camera",
        "If_you_remove_this_camera,":"hr-If you remove this camera,",
        "this_camera?":"hr-this camera?",
        "CLONE - ":"hr-CLONE - ",
        "Video Resolution":"hr-Video Resolution",
        "Bit Rate":"hr-Bit Rate",
        "High":"hr-High",
        "Low":"hr-Low",
        "Medium":"hr-Medium",
        "Video Cut Size":"hr-Video Cut Size",
        "1 hour":"hr-1 hour",
        "2 hour":"hr-2 hour",
        "3 hour":"hr-3 hour",
        "Video Pre-Buffer":"hr-Video Pre-Buffer",
        "Enable Video Pre-Buffer":"hr-Enable Video Pre-Buffer",
        "10 sec":"hr-20 sec",
        "20 sec":"hr-20 sec",
        "30 sec":"hr-30 sec",
        "60 sec":"hr-60 sec",
        "120 sec":"hr-120 sec",
        "180 sec":"hr-180 sec",
        "240 sec":"hr-240 sec",
        "300 sec":"hr-300 sec",
        "360 sec":"hr-360 sec",
        "420 sec":"hr-420 sec",
        "480 sec":"hr-480 sec",
        "540 sec":"hr-540 sec",
        "600 sec":"hr-600 sec",
        "Mute Audio Pre-Buffer":"hr-Mute Audio Pre-Buffer",
        "Video Overlay":"hr-Video Overlay",
        "Enable Video Overlay":"hr-Enable Video Overlay",
        "Date and Time":"hr-Date and Time",
        "Date ,Time and User":"hr-Date ,Time and User",
        "Unit , Date and Time":"hr-Unit , Date and Time",
        "User , Unit , Date and Time":"hr-User , Unit , Date and Time",
        "Recording Beep Interval":"hr-Recording Beep Interval",
        "Enable Recording Beep":"hr-Enable Recording Beep",
        "Vibration":"hr-Vibration",
        "Recording Vibration":"hr-Recording Vibration",
        "Device Controls":"hr-Device Controls",
        "Add All":"hr-Add All",
        "Category 1":"hr-Category 1",
        "Category 2":"hr-Category 2",
        "Category 3":"hr-Category 3",
        "Category 4":"hr-Category 4",
        "Enabled":"hr-Enabled",
        "Disabled":"hr-Disabled",
        "Always Muted":"hr-Always Muted",
        "(“Always Muted” will disable “Disable Audio Only Recording” checkbox)":"hr-(“Always Muted” will disable “Disable Audio Only Recording” checkbox)",
        "Disable Audio Only Recording":"hr-Disable Audio Only Recording",
        "Bookmark":"hr-Bookmark",
        "Disable Mark":"hr-Disable Mark",
        "Disable Wi-Fi and Bluetooth":"hr-Disable Wi-Fi and Bluetooth",
        "(If selected will disable �Enable GPS� checkbox section)":"hr-(If selected will disable �Enable GPS� checkbox section)",
        "Enable GPS":"hr-Enable GPS",
        "How often BC04 sends heartbeats":"hr-How often BC04 sends heartbeats",
        "How often <Body Worn Type> sends heartbeats":"hr-How often <Body Worn Type> sends heartbeats",
        "GPS Heartbeat":"hr-GPS Heartbeat",
        "(Minimum allowed is 30 and maximum allowed is 3600)":"hr-(Minimum allowed is 30 and maximum allowed is 3600)",
        "Too Low":"hr-Too Low",
        "Too High":"hr-Too High",
        "GPS Heartbeat While Recording":"hr-GPS Heartbeat While Recording",
        "Interval between heartbeats when recording":"hr-Interval between heartbeats when recording",
        "Enable LTE":"hr-Enable LTE",
        "Private APN":"hr-Private APN",
        "APN Name":"hr-APN Name",
        "APN":"hr-APN",
        "Proxy":"hr-Proxy",
        "Port":"hr-Port",
        "User Name":"hr-User Name",
        "Server":"hr-Server",
        "MMSC":"hr-MMSC",
        "MMSC Proxy":"hr-MMSC Proxy",
        "MMSC Port":"hr-MMSC Port",
        "MCC":"hr-MCC",
        "MNC":"hr-MNC",
        "Authentication Type":"hr-Authentication Type",
        "None":"hr-None",
        "PAP":"hr-PAP",
        "CHAP":"hr-CHAP",
        "PAP or CHAP":"hr-PAP or CHAP",
        "APN Type":"hr-APN Type",
        "Default":"hr-Default",
        "SUPL":"hr-SUPL",
        "MMS":"hr-MMS",
        "APN Protocol":"hr-APN Protocol",
        "IP":"hr-IP",
        "IPv4/IPv6":"hr-IPv4/IPv6",
        "APN Roaming Protocol":"hr-APN Roaming Protocol",
        "Template, ":"hr-Template, ",
        "Create_Template":"hr-Create Template : ",
        "Template_Sucessfully_Saved":"hr-Template Sucessfully Saved",
        "Template_with_this_name":"hr-Template with this name",
        "is_already_exists":"hr-is already exists",
        "Template_Edited_Sucessfully":"hr-Template Edited Sucessfully",
        "BC03_Template":"hr-BC03 Template",
        "Recording":"hr-Recording",
        "Mute":"hr-Mute",
        "categories is required":"hr-categories is required",
        "No_Template":"hr-No Template",
        "Serial_Number":"hr-Serial Number",
        "Version":"hr-Version",
        "Assigned_To":"hr-Assigned To",
        "Last_Checked_In":"hr-Last Checked In",
        "Template":"hr-Template",
        "File_Name":"hr-File Name",
        "Please_provide_a_valid_Unit_Id.":"hr-Please provide a valid Unit Id.",
        "Unit_Id_must_contains_atleast_three_characters.":"hr-Unit Id must contains atleast three characters.",
        "Unit_Id_must_not_exceed_128_characters.":"hr-Unit Id must not exceed 128 characters.",
        "Unit_Id_is_Required":"hr-Unit Id is Required",
        "Unit_Configuration_Template":"hr-Unit Configuration Template",
        "Unit_Detail":"hr-Unit Detail: ",
        "Unit_Edited_Sucessfully":"hr-Unit Edited Sucessfully",
        "Device_Name":"hr-Device Name",
        "Device_Type":"hr-Device Type",
        "Serial_Number":"hr-Serial Number",
        "Configurations":"hr-Configurations",
        "Queued_Assets":"hr-Queued_Assets",
        "ASSIGNED_TO":"hr-ASSIGNED TO",
        "ASSETS":"hr-ASSETS",
        "UPLOADING":"hr-UPLOADING", 
        "STATION":"hr-STATION",
        "CURRENT_VERSION":"hr-CURRENT VERSION",
        "SERIAL_NUMBER":"hr-SERIAL NUMBER",
        "STATUS":"hr-STATUS",
        "PRIMARY_UNIT_DEVICE":"hr-PRIMARY UNIT DEVICE",
        "Exit":"hr-Exit",
        "test":"hr-test",
        "UNREGISTERED":"hr-UNREGISTERED",
        "Edit_Configuration":"hr-Edit <Configuration>",
        "Assign_user(s)":"hr-Assign user(s)",
        "Deactivate":"hr-Deactivate",
        "Devices":"hr-Devices",
        "Queued_Assets":"hr-Queued Assets",
        "Units_&_Devices":"hr-Units & Devices",
        //--------------
        "Unit_Details":"hr-Unit Details",
        "'unit_configuration_form'":"hr-'unit configuration form'",
        "Configuration":"hr-Configuration",
        "Events":"hr-Events",
        "Device_Diagnostic":"hr-Device Diagnostic",
        "Update_History":"hr-Update History",
        "Unit Template":"hr-Unit Template",
        "LTE Settings":"hr-LTE Settings",
        "Template Information":"hr-Template Information",
        "Unit Settings":"hr-Unit Settings",
        "Primary Device":"hr-Primary Device",
        "CameraSetup":"hr-CameraSetup",
        "Camera Setup":"hr-Camera Setup",

    
           // --------- Share Asset ----------
           "Link_Expiration":"Link Expiration",
           "Link_Permissions":"Link Permissions",
           "Comments":"Comments",
           "Reason_for_Sharing":"Reason for Sharing",

      }
    }
  };