export const resources = {
    isr: {
      translation: {
        // --------- Asset Lister ----------
        "Login To Getac Enterprise using Getac Authentication":"hr-Login To Getac Enterprise using Getac Authentication",
        "Inspiring statement about Getac / Getac product that is relevant to user":"hr-Inspiring statement about Getac / Getac product that is relevant to user",
        "You are accessing a restricated information system. Your usage may be monitored, recoreded and subject to audit. Unauthorized use of the system is prohibited and may be subject to criminal and/or civil penalities. By using this system and clicking Log In, you consent to your usage being monitored and recorded.":"hr-You are accessing a restricated information system. Your usage may be monitored, recoreded and subject to audit. Unauthorized use of the system is prohibited and may be subject to criminal and/or civil penalities. By using this system and clicking Log In , you consent to your usage being monitored and recorded.",
        "Log_In":"hr-Log In",
        "assetDataTable":"hr-Assets",
        "userGroup_DataTable":"hr-User Groups",
        "Tables_columns_filter":"hr-Tables columns filter",
        "Close":"hr-Close",
        "Reset_to_default":"hr-Reset to default",
        "Clearall_filters":"hr-Clear all filters",
        "Customize_columns":"hr-Customize columns",
        "Save_and_close":"hr-Save and close",
        "Saveas_preset":"hr-Save as preset",
        "Actions":"hr-Actions",
        "ID":"hr-ID",
        "Asset_Thumbnail":"hr-Asset Thumbnail",
        "Asset_ID":"hr-Asset ID",
        "Asset_Type":"hr-Asset Type",
        "Unit":"hr-Unit",
        "Category":"hr-Category",
        "Description":"hr-Description",
        "Retention_Span":"hr-Retention Span",
        "Device":"hr-Device",
        "Station":"hr-Station",
        "Recorded_By":"hr-Recorded By",
        "User_Name":"hr-Username",
        "Captured":"hr-Captured",
        "File_Status":"hr-File Status",
        "Select_All":"hr-Select all",
        "Grouped_Assets":"hr-Grouped Assets",
        "Assign_User":"hr-Assign User",
        "Modify_Retention":"hr-Modify Retention",
        "Share_Asset":"hr-Share Asset",
        "Add_to_asset_bucket":"hr-Add to asset bucket",
        "Edit_Category_and_Form":"hr-Edit Category and Form",
        "Categorize":"hr-Categorize",
        "Email":"hr-Email",
        "File":"hr-File",
        "Metadata":"hr-",
        "Evidence_overlaid_video":"hr-Evidence overlaid video",
        "Metadata_overlaid_video":"hr-Metadata overlaid video",
        "Link_asset":"hr-Link asset",
        "Link_to_this_group":"hr-Link to this group",
        "Move_asset":"hr-Move asset",
        "Move_to_this_group":"hr-Move to this group",
        "Restrict_access":"hr-Restrict access",
        "Remove_from_asset_bucket":"hr-Remove from asset bucket",
        "Set_as_primary_asset":"hr-Set as primary asset",
        "Assign_to_case":"hr-Assign to case",
        "TBD":"hr-TBD",
        "Open_in_Getac_AI_tools_App":"hr-Open in Getac AI tools App",
        "Users":"hr-Users",
        "Apply_to_all_assets_in_the_group":"hr-Apply to all assets in the group",
        "Save":"hr-Save",
        "Cancel":"hr-Cancel",
        "You_are_attempting_to":"hr-You are attempting to",
        "close":"hr-close",
        "the_modal_dialog":"hr-the modal dialog.",
        "If_you_close_the_modal_dialog,":"hr-If you close the modal dialog,",
        "any_changes_you_ve_made_will_not_be_saved.":"hr-any changes you've made will not be saved.",
        "You_will_not_be_able_to_undo_this_action.":"hr-You will not be able to undo this action.",
        "Are_you_sure_you_would_like_to":"hr-Are you sure you would like to",
        "Yes":"hr-Yes",
        "No,_do_not_close":"hr-No, do not close",
        "Success:_You_have_saved_the_asset_categorization":"hr-Success: You have saved the asset categorization",
        "Error_We_re_sorry._The_form_was_unable_to_be_saved._Please_retry_or_contact_your_Systems_Administrator":"hr-Error: We're sorry. The form was unable to be saved. Please retry or contact your Systems Administrator",
        "Indicates_required_field":"hr-Indicates required field",
        "Please_enter_the_reason_for_editing_the_form.":"hr-Please enter the reason for editing the form.",
        "Category_form_edit_reason":"hr-Category form edit reason",
        "Editing_the_category_form_requires_a_reason":"hr-Editing the category form requires a reason",
        "Please_confirm":"hr-Please confirm",
        "Please_be_aware_that_by_removing_this_category,_you_are_reducing_the_assets_lifetime_and_the_asset_will_expire":"hr-Please be aware that by removing this category, you are reducing the assets lifetime and the asset will expire",
        "in":"hr-in",
        "Hours.":"hr-Hours.",
        "Please_be_aware_that_by_removing_this_category,_you_are_reducing_the_assets_lifetime_and_the_asset_will_expire_in":"hr-Please be aware that by removing this category, you are reducing the assets lifetime and the asset will expire in",
        "Unclassified_retention_policy_of_station_will_be_applied_on_this_evidence_group.":"hr-Unclassified retention policy of station will be applied on this evidence group.",
        "Success_You_have_saved_the_asset_categorization":"hr-Success: You have saved the asset categorization",
        "We_re_sorry._The_form_was_unable_to_be_saved._Please_retry_or_contact_your_Systems_Administrator":"hr-We 're sorry. The form was unable to be saved. Please retry or contact your Systems Administrator",
        "You_are_attempting_to_remove":"hr-You are attempting to remove",
        "Do_you_want_you_continue_with_removing_the_category?":"hr-Do you want you continue with removing the category?",
        "Yes,_remove-category":"hr-Yes, remove category",
        "No,_do_not_remove_category":"hr-No, do not remove category",
        "category":"hr-category",
        "Category_Title_Placeholder_Here":"hr-Category Title Placeholder Here",
        "Attention":"hr-Attention",
        "There_is_no_form_response_for_the_category_named,":"hr-There is no form response for the category named,",
        "Please_sav_to_continue.":"hr-Please save to continue.",
        "Back":"hr-Back",
        "Required":"hr-Required",
        "Category_Forms":"hr-Category Forms",
        "is_required":"hr-is required",
        "Category_form":"hr-Category form'",
        "Edit_category":"hr-Edit category",
        "Next":"hr-Next",
        "Skip_category_form_and_save":"hr-Skip category form and save",
        "Choose_Category":"hr-Choose Category",
        "From_the_field_below,_select_one_or_more_relevant_category.":"hr-From the field below, select one or more relevant category.",
        "Removing_the_category_requires_a_reason":"hr-Removing the category requires a reason",
        "Please_enter_the_reason_for_removing_the_category.":"hr-Please enter the reason for removing the category.",
        "Category_removal_reason":"hr-Category removal reason",
        "Extend_retention_by_days":"hr-Extend retention by days",
        "Extend_retention_Indefinitely":"hr-Extend retention Indefinitely",
        "User":"hr-User",
        "Revert_to_original_retention":"hr-Revert to original retention",
        "Retention_Extended":"hr-Retention Extended",
        "Retention_Reverted":"hr-Retention Reverted",
        "Original_Retention:":"hr-Original Retention:",
        "Current_Retention:":"hr-Current_Retention:",
        "Extend":"hr-Extend",
        "Assets":"hr-Assets",
        "Search_assets_by_ID#_case#_CAD#_categories_etc.":"hr-Search assets by ID#, case#, CAD#, categories, etc.",
        "Infinite":"hr-Infinite",
        "Days":"hr-Days",
        "Hours":"hr-Hours",
        "Share_email_sent_to_recipients":"hr-Share email sent to recipients",
        "Include_Metadata":"hr-Include Metadata",
        "Link_Expiry":"hr-Link Expiry",
        "Viewable_once":"hr-Viewable once",
        "Downloadable":"hr-Downloadable",
        "Please_Select":"hr-Please Select",
        "Search_by":"hr-Search by",
        "Date_and_Time":"hr-Date and Time",
        "Add_search_criteria":"hr-Add search criteria",
        "Reset_advanced_search":"hr-Reset advanced search",
        "Advanced_Search":"hr-Advanced Search",
        "day":"hr-day",
        "days":"hr-days",
        "second":"hr-second",
        "Search_Results":"hr-Search Results",
        "next_30_days":"hr-next 30 days",
        "Search_Assets":"hr-Search Assets",
        "Search":"hr-Search",
        "Confirm":"hr-Confirm",
        "Are_you_sure_want_to_restrict_access_to_the_selected_asset(s)?":"hr-Are you sure want to restrict access to the selected asset(s)?",
        "Access_to_the_selected_asset(s)_will_be_restricted_to_user_groups_with_the_view_locked_asset_permission.":"hr-Access to the selected asset(s) will be restricted to user groups with the view locked asset permission.",
        "Delete":"hr-Delete",
        "the":"hr-the",
        "Notes":"hr-Notes",
        "Bookmark":"hr-Bookmark",
        "action":"hr-action",
        "the_dialogue?":"hr-the dialogue?",
        "Form":"hr-Form",
        "Edit":"hr-Edit",
        "Showless":"hr-Showless",
        "Read_More":"hr-Read More",
        "Map":"hr-Map",
        "Bookmarks":"hr-Bookmarks",
        "Success":"hr-Success",
        "Note_Sucessfully_Updated":"hr-Note Sucessfully Updated ",
        "Bookmark_Edited_Sucessfully":"hr-Bookmark Edited Sucessfully ",
        "Bookmark_Deleted_Sucessfully":"hr-Bookmark Deleted Sucessfully ",
        "Note_Deleted_Sucessfully":"hr-Note Deleted Sucessfully ",
        "Search_Bookmark":"hr-Search Bookmark",
        "Search_by_Name_keyword_etc.":"hr-Search by Name, keyword, etc.",
        "Search_Notes":"hr-Search Notes",
        "Asset_Detail:_":"hr-Asset Detail: ",
        "Information":"hr-Information",
        "GROUPED_AND_RELATED_ASSETS":"hr-GROUPED AND RELATED ASSETS",
        "Captured_Date":"hr-Captured Date",
        "Owners":"hr-Owners",
        "Unit":"hr-Unit",
        "CheckSum":"hr-CheckSum",
        "Video_Duration":"hr-Video Duration",
        "Size":"hr-Size",
        "Retention":"hr-Retention",
        "Categories":"hr-Categories",
        "Copyright_©_Getac_Video_Solutions_Inc._and_its_subsidiaries._All_rights_reserved._|_Enterprise_Version":"hr-Copyright © Getac Video Solutions, Inc. and its subsidiaries. All rights reserved. | Enterprise Version",
        "is_successfully_set_as_primary_asset":"hr-is successfully set as primary asset",
        "You_are_sure_want_to_make":"hr-You are sure want to make",
        "the_primary_asset?":"hr-the primary asset?",
        "Set_as_primary_asset":"hr-Set as primary asset",
        "Export":"hr-Export",
        "Asset_Assignees_updated":"hr-Asset Assignees updated",
        // -------------------------

        // --------- User ----------
        "Send_Activation_Link":"hr-Send Activation Link",
        "Resend_Activation_Link":"hr-Resend Activation Link",
        "Generate":"hr-Generate",
        "Copy":"hr-Copy",
        "Require_user_to_change_password_on_next_login":"hr-Require user to change password on next login",
        "Password":"hr-Password",
        "Confirm_Password":"hr-Confirm Password",
        "Generate_Temporary_Password":"hr-Generate Temporary Password",
        "Manually_Set_Password":"hr-Manually Set Password",
        "You_have_created_the_user_account.":"hr-You have created the user account.",
        "You_have_resent_the_activation_link.":"hr-You have resent the activation link.",
        "You_have_updated_the_user_account.":"hr-You have updated the user account.",
        "Please_provide_a_valid_User_name.":"hr-Please provide a valid User name.",
        "User_name_must_contain_atleast_three_characters.":"hr-User name must contain atleast three characters.",
        "User_name_must_not_exceed_128_characters.":"hr-User name must not exceed 128 characters.",
        "Please_provide_a_valid":"hr-Please provide a valid",
        "must_contain_atleast_three_characters.":"hr-must contain atleast three characters.",
        "must_not_exceed_128_characters.":"hr-must not exceed 128 characters.",
        "First_Name":"hr-First Name",
        "First_Name_is_required":"hr-First Name is required",
        "Last_Name":"hr-Last Name",
        "Last_Name_is_required":"hr-Last Name is required",
        "Username_is_required":"hr-Username is required",
        "Email_is_required":"hr-Email is required",
        "Please_provide_a_valid_email_address":"hr-Please provide a valid email address",
        "Password_is_required":"hr-Password is required",
        "Confirm_Password_is_required":"hr-Confirm Password is required",
        "Passwords_are_not_same":"hr-Passwords are not same",
        "(Link_will_be_sent_after_saving_this_form.)":"hr-(Link will be sent after saving this form.)",
        "Please_provide_a_valid_phone_number.":"hr-Please provide a valid phone number.",
        "Number_must_not_exceed_15_characters.":"hr-Number must not exceed 15 characters.",
        "User_group_is_required":"hr-User group is required",
        "Middle_Initial":"hr-Middle Initial",
        "Phone_Number":"hr-Phone Number",
        "User_Group":"hr-User Group",
        "Deactivation_Date":"hr-Deactivation Date",
        "User_Password_Setup":"hr-User Password Setup",
        "'user_form'":"hr-'user form'",
        "If_you_close_the_form":"hr-If you close the form",
        "the_form?":"hr-the form?",
        "Yes_close":"hr-Yes, close",
        "custom_range":"hr-custom range",
        "No_Status":"hr-No Status",
        "Status":"hr-Status",
        "Last_Login":"hr-Last Login",
        "Groups":"hr-Groups",
        "Create_User":"hr-Create User",
        "Filter":"hr-Filter",
        "Unlock_user_account":"hr-Unlock user account",
        "Yes_unlock_user_account":"hr-Yes, unlock user account",
        "No_do_not_unlock":"hr-No, do not unlock",
        "Deactivate_user_account":"hr-Deactivate user account",
        "Yes_deactivate_user_account":"hr-Yes, deactivate user account",
        "No_do_not_deactivate":"hr-No, do not deactivate",
        "You_have_unlocked_the_user_account.":"hr-You have unlocked the user account.",
        "You_have_deactivated_the_user_account.":"hr-You have deactivated the user account.",
        "Assets_Action_Menu":"hr-Assets Action Menu",
        "the_following_user_account:":"hr-the following user account:",
        "Please_confirm_if_you_would_like_to":"hr-Please confirm if you would like to",
        "this_user_account.":"hr-this user account.",
        "Edit_user":"hr-Edit user",
        "Unlock_account":"hr-Unlock account",
        "Deactivate_account":"hr-Deactivate account",
        // ------------------------------

        // --------- User Group----------
        "Group_Name":"hr-Group Name",
        "Total_Users_Assigned":"hr-Total Users Assigned",
        "Create_Group":"hr-Create Group",
        "GROUP_NAME":"hr-GROUP NAME",
        "USERS":"hr-USERS",
        "APPLICATION_PERMISSIONS":"hr-APPLICATION PERMISSIONS",
        "DATA_PERMISSIONS":"hr-DATA PERMISSIONS",
        "User_group_saved_successfully.":"hr-User group saved successfully.",
        "We_re_sorry_The_group_information_users_and_application_permissions_were_unable_to_be_saved__Please_retry_or_contact_your_System_Administrator.":"hr-We're sorry. The group information, users, and application permissions were unable to be saved. Please retry or contact your System Administrator.",
        "We_re_sorry_The_data_permissions_were_unable_to_be_saved._Please_retry+or_contact_your_System_Administrator.":"hr-We're sorry. The data permissions were unable to be saved. Please retry or contact your System Administrator.",
        "'user_group_form'":"hr-'user group form'",
        "Module_Names":"hr-Module Names",
        "Basic_level":"hr-Basic level",
        "Advanced_level":"hr-Advanced level",
        "Restricted_level":"hr-Restricted level",
        "Apply_application_permissions_from":"hr-Apply application permissions from",
        "All":"hr-All",
        "Uncategorized":"hr-Uncategorized",
        "No_Station":"hr-No Station",
        "Permission_Type":"hr-Permission Type",
        "Permission_Value":"hr-Permission Value",
        "Permission_Level":"hr-Permission Level",
        "Add_data_permissions":"hr-+ Add data permissions",
        "Group_name_is_required":"hr-Group name is required",
        "No_Groups":"hr-No Groups",
        // ----------------------------
        
        // --------- Station ----------
        "Address":"hr-Address",
        "Create_Station":"hr-Create Station",
        "Station_deleted":"hr-Station deleted",
        "The_station_cant_be_deleted__please_check_for_dependent_units_and_assets":"hr-The station can't be deleted, please check for dependent units and assets",
        "Delete_station":"hr-Delete station",
        "No":"hr-No",
        "unlock":"hr-unlock",
        "deactivate":"hr-deactivate",
        "delete":"hr-delete",
        "the_following_user_account":"hr-the following user account",
        "You_are_attempting_to_delete_the_station":"hr-You are attempting to delete the station",
        "Are_you_sure_you_would_like_to_delete_the_station?":"hr-Are you sure you would like to delete the station?",
        "Edit_station":"hr-Edit station",
        "View_default_unit_templates":"hr-View default unit templates",
        "Station_Name_is_required":"hr-Station Name is required",
        "Minimum_5_characters_are_allowed.":"hr-Minimum 5 characters are allowed.",
        "Pass_Code_is_required":"hr-Pass Code is required",
        "Only_alphabets_and_digits_are_allowed.":"hr-Only alphabets and digits are allowed.",
        "Success_You_have_saved_the_Station":"hr-Success: You have saved the Station",
        "Station_Name":"hr-Station Name",
        "Name":"hr-Name",
        "Latitude":"hr-Latitude",
        "Longitude":"hr-Longitude",
        "Location":"hr-Location",
        "Map_location":"hr-Map location",
        "Street_Address":"hr-Street Address",
        "Pass_Code":"hr-Pass Code",
        "Station_Settings":"hr-Station Settings",
        "Data_Retention_Policy":"hr-Data Retention Policy",
        "Retention_Policy_is_required":"hr-Retention Policy is required",
        "Data_Upload_Policy":"hr-Data Upload Policy",
        "Upload_Policy_is_required":"hr-Upload Policy is required",
        "BlackBox_Retention_Policy":"hr-BlackBox Retention Policy",
        "SSID":"hr-SSID",
        "Unit_Templates":"hr-Unit Templates",
        "Select_location_on_the_map":"hr-Select location on the map",
        "Save_Location":"hr-Save Location",
        "Phone_Number_is_not_valid!":"hr-Phone Number is not valid!",
        "Phone_Number":"hr-Phone Number",
        // -------------------------
        
        // --------- Unit ----------
        "To_Get_ID":"hr-To Get ID",
        "Success_You_have_saved_the_Default_Unit_Template":"hr-Success: You have saved the Default Unit Template",
        "Manage_Default_Unit_Template":"hr-Manage Default Unit Template",
        "Manage_Unit_Configuration":"hr-Manage Unit Configuration",
        "Edit_template":"hr-Edit template",
        "Clone_template":"hr-Clone template",
        "Delete_template":"hr-Delete template",
        "View_Change_Log":"hr-View Change Log",
        "Are_you_sure_you_would_like_to_delete_template?":"hr-Are you sure you would like to delete template?",
        "template":"hr-template",
        "this":"hr-this",
        "No_Version":"hr-No Version",
        "No_type":"hr-No type",
        "Default":"hr-Default",
        "No_Indicator":"hr-No Indicator",
        "Type":"hr-Type",
        "Indicator":"hr-Indicator",
        "Create_Template":"hr-Create Template",
        "Change_Log":"hr-Change Log: ",
        "Changes":"hr-Changes",
        "Log_Time":"hr-Log Time",
        // ---------------------------
        
        // --------- Header ----------
        "Getac_Command":"hr-Getac Command",
        "Getac_Enterprise":"hr-Getac Enterprise",
        "All_Stations":"hr-All Stations",
        "Departments":"hr-Departments",
        "Help":"hr-Help",
        "User_Profile":"hr-User Profile",
        "Logout":"hr-Logout",
        "Home":"hr-Home",
        "Cases":"hr-Cases",
        "Units_&_Devices":"hr-Units & Devices",
        "ALPR":"hr-ALPR",
        "Plate_Captures":"hr-Plate Captures",
        "Live_ALPR":"hr-Live ALPR",
        "Manage_Hot_List":"hr-Manage Hot List",
        "Manage_Hot_List_Data_Source":"hr-Manage Hot List Data Source",
        "Manage_License_Plates":"hr-Manage License Plates",
        "Admin":"hr-Admin",
        "Manage_User_Groups_Permissions":"hr-Manage User Groups & Permissions",
        "Manage_Users":"hr-Manage Users",
        "Manage_Device_Unit_Templates":"hr-Manage Device & Unit Templates",
        "Evidence(Dev)":"hr-Evidence(Dev)",
        "Manage_Station":"hr-Manage Station",
        // ---------------------------------
        
        // --------- Asset buctet ----------
        "An_asset_you_are_attempting_to_add_to_the_asset_bucket_has_already_been_added.":"hr-An asset you are attempting to add to the asset bucket has already been added.",
        "You_have_added_the_selected_assets_to_the_asset_bucket.":"hr-You have added the selected assets to the asset bucket.",
        "assets":"hr-assets",
        "asset":"hr-asset",  
        "removed_the_asset_bucket":"hr-removed the asset bucket",
        "Asset_Bucket_can_be_used_to_build_cases_and_do_one_action_on_many_assets_at_the_same_time.":"hr-Asset Bucket can be used to build cases and do one action on many assets at the same time.",
        "Asset_Bucket":"hr-Asset Bucket",
        "Minimum_3_and_maximum_128_characters_are_allowed":"hr-Minimum 3 and maximum 128 characters are allowed",
        "Only_alphabets_digits_and_,_-_are_allowed._Must_start_with_an_alphabet_only":"hr-Only alphabets, digits and _, - are allowed. Must start with an alphabet only",
        "File(s)_failed_to_upload.":"hr-File(s) failed to upload.",
        "File(s)_uploaded":"hr-File(s) uploaded",
        "Asset_saved":"hr-Asset_saved",
        "File_has_been_removed_successfully":"hr-File has been removed successfully",
        "Your_Asset_Bucket":"hr-Your Asset Bucket",
        "Please_add_metadata_to_finish_saving_your_uploaded_files":"hr-Please add metadata to finish saving your uploaded files",
        "Add_metadata":"hr-Add metadata",
        "Choose_asset_metadata_edited-on-purpose":"hr-Choose asset metadata edited-on-purpose",
        "Drag_and_drop_an":"hr-Drag and drop an",
        "to_the_Asset_Bucket_to_add_or_use_the":"hr-to the Asset Bucket to add, or use the",
        "file_browser":"hr-file browser",
        "Upload_Details":"hr-Upload Details",
        "View_on_assets_bucket_page":"hr-View on assets bucket page",
        "Your_Asset_Bucket_is_empty.":"hr-Your Asset Bucket is empty.",
        "Yes_remove":"hr-Yes, remove",
        "No_do_not_remove":"hr-No, do not remove",
        "remove":"hr-remove",
        "the_file":"hr-the file",
        "Once_you_remove_it":"hr-Once you remove it",
        "asset_from_this_upload.":"hr-asset from this upload.",
        "this_asset_from_this_upload?":"hr- this asset from this upload?",
        "owner(s)_are_required":"hr-owner(s) are required",
        "This_field_is_required!":"hr-This field is required!",
        "Master_Asset":"hr-Master Asset",
        "Select_Master_Asset":"hr-Select_Master_Asset",
        "Category_Title_Placeholder_Here":"hr-Category Title Placeholder Here",
        "There_is_no_form_response_for_the_category_named":"hr-There is no form response for the category named",
        "Please_save_to_continue":"hr-Please save to continue",
        // ---------------------------------
        
        // --------- Global Search ----------
        "Global_Search":"hr-Global Search",
        // ---------------------------------
        
        // ---------  Notifications ----------
        "Search_assets_by_ID_case_CAD_categories_etc":"hr-Search assets by ID#, case#, CAD#, categories, etc",
        "Notifications":"hr-Notifications",
        "Clear_All":"hr-Clear All",
        // -------------------------
        
        // --------- Constant ----------
        "Deleted":"hr-Deleted",
        "Trash":"hr-Trash",
        "Not_Categorized":"hr-Not Categorized",
        "Approaching_Deletion":"hr-Approaching Deletion",
        "SimpleSearch":"hr-SimpleSearch",
        "AdvanceSearch":"hr-AdvanceSearch",
        "ShortcutSearch":"hr-ShortcutSearch",
        "Unit_ID":"hr-Unit ID",
        "UnCategorized":"hr-UnCategorized",
        // -------------------------
        
        // --------- Data Table ----------
        "Tables_columns_filter":"hr-Tables columns filter",
        "Clear_all_filters":"hr-Clear all filters",
        "Basic":"hr-Basic",
        "Advance":"hr-Advance",
        "Restrictive":"hr-Restrictive",
        "total_users_in_group":"hr-total users in group",
        "":"hr-",

      }
    }
  };