export const resources = {
    uk: {
      translation: {
        "Login To Getac Enterprise using Getac Authentication":"Login To Getac Enterprise using Getac Authentication",
        "Inspiring statement about Getac / Getac product that is relevant to user":"Inspiring statement about Getac / Getac product that is relevant to user",
        "You are accessing a restricated information system. Your usage may be monitored, recoreded and subject to audit. Unauthorized use of the system is prohibited and may be subject to criminal and/or civil penalities. By using this system and clicking Log In, you consent to your usage being monitored and recorded.":"You are accessing a restricted information system. Your usage may be monitored, recorded and subject to audit. Unauthorized use of the system is prohibited and may be subject to criminal and/or civil penalties. By using this system and clicking “Log In”, you consent to your usage being monitored and recorded.",
        "Log In":"Log In",
        "assetDataTable": "fr-Assets",
        "userGroupDataTable": "fr-User Groups",
        "Tablescolumnsfilter": "fr-Table columns filter",
        "Close" : "fr-Close",
        "Resettodefault" : "fr-Reset to default",
        "Clearallfilters": "fr-Clear all filters",
        "Customizecolumns": "fr-Customize columns",
        "Saveandclose" : "fr-Save and close",
        "Saveaspreset" : "fr-Save as preset",
        "Actions": "fr-Actions",
        "ID":"fr-ID",
        "AssetThumbnail":"fr-Asset Thumbnail",
        "AssetID":"fr-Asset ID",
        "AssetType":"fr-Asset Type",
        "Unit":"fr-Unit",
        "Categories":"fr-Category",
        "Device":"fr-Device",
        "Station":"fr-Station",
        "Recorded By":"fr-Recorded By",
        "Captured":"fr-Captured",
        "FileStatus":"fr-File Status",
        "SelectAll":"fr-Select All",
        "GroupedAssets":"fr-Grouped Assets",
        "Download_link":"fr-Download Link",
        "Asset_name":"fr-Asset Name",
        "Unit_name":"fr-Unit Name",
      }
    }
  };